### ISSUE TITLE
never stops running

### ISSUE THREAD

**Issue by i300220** [desktop/desktop#11455]
### Describe the bug

After closing github dsktop, 4 tasks continue to run in the background.  They can't be killed.  Trying to restart github desktop only creates more zombie tasks.  The only cure is to reboot (logging off is not enough).

### Version & OS

Latest 2.6.2 running on windows 7 ultimate 64
https://desktop.githubusercontent.com/releases/2.6.2-a01e1223/GitHubDesktopSetup.exe

### Steps to reproduce the behavior

1. Close github desktop
2. open windows task manager
3. switch to the processes tab
3. Scroll down to 'git'
4. Try to kill git*
5. Try to restart github desktop
6. goto 3. where more git* will be present

### Expected behavior

When program is exited, the memory should be cleared and the program
trminated.  It should start again when restarted.

Uninstalling / reinstalling did not fix a thing.

### Screenshots

![Clipboard01](https://user-images.githubusercontent.com/15702355/105644712-fda32480-5e64-11eb-98a5-292460542a90.jpg)

### Logs

Can't start the program when it's zombified.

### Additional context
N/A

**Comment by steveward** [comment]
Thanks for the report @i300220. We've seen cases of lingering processes in the past -- have you tried performing a fresh installation of GitHub Desktop to see if that helps? I see you did try reinstalling, but I wanted to confirm whether or not a fresh installation helped.

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

**Comment by steveward** [comment]
@i300220 it'd also be helpful if you could grab a log file from `%AppData%\GitHub Desktop\logs`. Even if you can't launch the application the log files should be there. Please upload one from a day you experienced this issue. Thanks!

**Comment by i300220** [comment]
Well, I uninstalled with  BCUninstaller which requires 2 passes.  There is nothing left of the dirctories you've mentioned.  Then I reinstalled, had to reimport all my repos, reconfigure everything and was unable to exit properly.  Then I used BCUninstaller again to delete everything related, even stuff in th registry and all related directories.  All is left is  C:\Users\shizuma\AppData\Local\SquirrelTemp\SquirrellSetup.log

The pertinent part follows:

2020-12-13 12:14:52> Program: Starting Squirrel Updater: --install .
2020-12-13 12:14:52> Program: Starting install, writing to C:\Users\shizuma\AppData\Local\SquirrelTemp
2020-12-13 12:14:52> Program: About to install to: C:\Users\shizuma\AppData\Local\GitHubDesktop
2020-12-13 12:14:53> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\shizuma\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-12-13 12:14:53> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\shizuma\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-12-13 12:14:53> CheckForUpdateImpl: Reading RELEASES file from C:\Users\shizuma\AppData\Local\SquirrelTemp
2020-12-13 12:14:53> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-12-13 12:14:53> ApplyReleasesImpl: Writing files to app directory: C:\Users\shizuma\AppData\Local\GitHubDesktop\app-2.6.0
2020-12-13 12:14:55> LogHost: Rigging execution stub for GitHubDesktop_ExecutionStub.exe to C:\Users\shizuma\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2020-12-13 12:14:59> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\shizuma\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe]
2020-12-13 12:15:01> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: BlackHawk Web Browser.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: Calculator.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: Epic Privacy Browser.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: IrfanView 64.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: ManyCam.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: MX5.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: Opera Browser.lnk
2020-12-13 12:15:01> ApplyReleasesImpl: Examining Pin: Pale Moon.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: PuTTY.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: QtWeb Internet Browser.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: Start Tor Browser.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: Sticky Notes.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: Sublime Text 3.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: Vivaldi.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Examining Pin: Windows Task Manager.lnk
2020-12-13 12:15:02> ApplyReleasesImpl: Fixing up tray icons
2020-12-13 12:15:02> ApplyReleasesImpl: cleanDeadVersions: for version 2.6.0
2020-12-13 12:15:02> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.6.0
2021-01-24 16:34:24> Program: Starting Squirrel Updater: --install .
2021-01-24 16:34:24> Program: Starting install, writing to C:\Users\shizuma\AppData\Local\SquirrelTemp
2021-01-24 16:34:24> Program: About to install to: C:\Users\shizuma\AppData\Local\GitHubDesktop
2021-01-24 16:34:24> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\shizuma\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2021-01-24 16:34:24> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\shizuma\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2021-01-24 16:34:24> CheckForUpdateImpl: Reading RELEASES file from C:\Users\shizuma\AppData\Local\SquirrelTemp
2021-01-24 16:34:24> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2021-01-24 16:34:24> ApplyReleasesImpl: Writing files to app directory: C:\Users\shizuma\AppData\Local\GitHubDesktop\app-2.6.2
2021-01-24 16:34:26> LogHost: Rigging execution stub for GitHubDesktop_ExecutionStub.exe to C:\Users\shizuma\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2021-01-24 16:34:30> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\shizuma\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe]
2021-01-24 16:34:31> ApplyReleasesImpl: Starting fixPinnedExecutables
2021-01-24 16:34:31> ApplyReleasesImpl: Examining Pin: BlackHawk Web Browser.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Brave.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Calculator.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Dissenter.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Epic Privacy Browser.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: IrfanView 64.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: ManyCam.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: MX5.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Opera Browser.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Pale Moon.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: PuTTY.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: QtWeb Internet Browser.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Start Tor Browser.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Sticky Notes.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Sublime Text 3.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Vivaldi.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Examining Pin: Windows Task Manager.lnk
2021-01-24 16:34:32> ApplyReleasesImpl: Fixing up tray icons
2021-01-24 16:34:32> ApplyReleasesImpl: cleanDeadVersions: for version 2.6.2
2021-01-24 16:34:32> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.6.2

It ends abruptly like this.  Hope that helps.

Best!

**Comment by steveward** [comment]
Thanks for the update @i300220. It's been a while since i've tested GitHub Desktop on Windows 7 -- I'll spin up my VM to see if I'm able to reproduce any issues.

Are you running any antivirus/security software on this machine?

**Comment by i300220** [comment]
Hi Steve,

I do,

Spyware Blaster and Comodo Internet security premium with antivirus disabled.  Only the firewall is set to training mode.  It gives warnings when it discovers an unknown program trying to run.  I don't recall seeing any for GD.  If I did, I gave it full access.  No doubt about it.

When I think I may need an antivirus, I run it manually, all along with Malwarebytes and SuperAntiSpyware.  Nothing automatic/resident/service but Comodo.  Did run them recently.  Took most of the day.

Furthermore DNS are resolved by a custom bind setup (debian 10) on my LAN.

All problems began when v 2.6.0 autoupdated to 2.6.2, which installed but never was able to start.  A reboot was required with checkdisk c:, checkfisk e:, etc.

Best!

**Comment by i300220** [comment]
Reinstalled v 2.6.0 with %appdata%\local\GitHubDesktop\ already opened and ready waiting for update.exe to appear.  Renamed it immediately and had a command line ready  - just to hit the Enter key - to kill it in case it's already started (it had).  Auto update ends right here.  Will stick to this version until it works no more.

**Comment by steveward** [comment]
Thanks for the info @i300220. I'd be curious if v2.6.3 also has this issue (released yesterday). I was unable to reproduce this in a test Windows 7 VM so my guess is it was either a broken update or a system configuration issue. I'm going to close this out but let me know if you still need any further assistance.

**Comment by i300220** [comment]
Thanks for your new release Steve.  I appreciate your work.

**Comment by ZoeWithTheE** [comment]
This is still an issue with the current version. GitHubUI.exe repeatedly opens when I launch VS code. I'm waiting for file explorer to find any and all mentions of both git and github so I can delete them all (if theyre not in another app). sh.cmd is listed in task manager too many times to count. I wouldnt be surprised if you told me there were thousands of instances of it running. on top of that, many other .exe processes were spawning at a rate faster than I could scroll, even with my free scroll toggled on my mouse. at least a few thousand processes were started, causing my system to crash, even with my Ryzen 9 5900x. this needs to be fixed as soon as possible.
If its any help, it only started after i enabled that tunneling feature in vs code. the one that allows u to access vs code on that machine via a browser.

Windows 10 - build 19045
Ryzen 9 5900x 12 core
64gb 3600mhz
git version 2.39.2, 64 bit

Hope this is of some help
