### ISSUE TITLE
Github Mac Doesn't Update

### ISSUE THREAD

**Issue by ckizer** [desktop/desktop#12818]
Github for Mac always tells me there is updates. Unfortunately they never install when I click on the banner. Here's the error log output:

**tail ~/Library/Caches/com.github.GitHubClient.ShipIt/ShipIt_stderr.log**

```
2020-11-18 13:06:09.855 ShipIt[59212:2010163] ShipIt quitting
2020-11-18 13:06:11.891 ShipIt[59215:2010221] Resuming installation attempt 3
2020-11-18 13:06:11.894 ShipIt[59215:2010223] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/ck/Library/Caches/com.github.GitHubClient.ShipIt/update.DjUzfa4/GitHub%20Desktop.app/ to directory file:///var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/com.github.GitHubClient.ShipIt.Up2AZQUj/GitHub%20Desktop.app" UserInfo={NSFilePath=/Users/ck/Library/Caches/com.github.GitHubClient.ShipIt/update.DjUzfa4/GitHub Desktop.app, NSLocalizedDescription=Failed to copy bundle file:///Users/ck/Library/Caches/com.github.GitHubClient.ShipIt/update.DjUzfa4/GitHub%20Desktop.app/ to directory file:///var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/com.github.GitHubClient.ShipIt.Up2AZQUj/GitHub%20Desktop.app, NSUnderlyingError=0x7fded800f490 {Error Domain=NSCocoaErrorDomain Code=260 "The file “GitHub Desktop.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/ck/Library/Caches/com.github.GitHubClient.ShipIt/update.DjUzfa4/GitHub Desktop.app, NSUnderlyingError=0x7fded800f3f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2020-11-18 13:06:11.894 ShipIt[59215:2010223] ShipIt quitting
2020-11-18 13:06:13.923 ShipIt[59219:2010273] Too many attempts to install, aborting update
2020-11-18 13:06:13.924 ShipIt[59219:2010275] ShipIt quitting

```

**Comment by sergiou87** [comment]
Hi @ckizer! 👋 

I might be mistaken, but sounds like you're using a really old and unsupported version of GitHub Desktop 😳  4 years ago the team (I just joined 8 months ago 😅 ) released a new version that you can download from https://desktop.github.com/

That one will auto update as soon as we release something new!

**Comment by ckizer** [comment]
**If anyone has similar Mac issues, this finally solved it for me**
https://github.com/desktop/desktop/issues/11705#issuecomment-790820197

I believe it was just that I was showing you the wrong error messages and I've renamed the App to match the old app name.

**The actual version I'm using was 2.6.6 that had the issues**

I tells me it's ready to quit and relaunch, but whenever I click quit, the app never reopens with the update

<img width="559" alt="ScreenShot 2021-08-23 at 04 30 44@2x" src="https://user-images.githubusercontent.com/191738/130440412-f3e25775-db6f-4976-9a4c-17c16db3d1c7.png">

**Comment by sergiou87** [comment]
@ckizer oh, ok! Glad you solved it. The logs you were showing also belonged to the old app, hence my confusion, sorry!

Regarding the app not reopening after the update, that was [an old issue with Electron and macOS Big Sur](https://github.com/electron/electron/issues/25626) and requires you to reopen manually, but was fixed on our side in when we updated to a newer version (2.7.0 I presume). From now on it should update & reopen 😄

**Comment by ckizer** [comment]
I stand corrected. It still doesn't update even with the latest client. It quits, but never reopens and still gives the error message. I there a permission somewhere I need to fix?

**When you see it reopening, that's me manually relaunching it from Spotify. It still thinks it never download the update each time.**

![ScreenShot 2021-08-25 at 03 22 41](https://user-images.githubusercontent.com/191738/130773939-b7c16095-02ef-472b-8078-6ef24dfe1293.gif)

**Comment by sergiou87** [comment]
🤯  That's definitely unexpected. Could you share the logs with me? You can find them in `Help` -> `Show logs in Finder`

![image](https://user-images.githubusercontent.com/1083228/130774873-1996d4a6-f71d-49ef-a8b4-22eabc87134e.png)

**Comment by ckizer** [comment]
```
2021-08-25T10:55:36.996Z - info: [ui] [AppStore] loading 4 repositories from store
2021-08-25T10:55:36.996Z - info: [ui] [AppStore] found account: ckizer (Court K)
2021-08-25T10:55:37.041Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-08-25T10:55:38.181Z - info: [ui] launching: 2.9.0 (Mac OS 12.0.0)
2021-08-25T10:55:38.182Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2021-08-25T10:55:38.870Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.847s)
2021-08-25T10:55:39.864Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.777s)
2021-08-25T10:56:02.773Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.631s)
2021-08-25T10:56:29.322Z - info: [ui] [AppStore] loading 4 repositories from store
2021-08-25T10:56:29.323Z - info: [ui] [AppStore] found account: ckizer (Court K)
2021-08-25T10:56:29.372Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-08-25T10:56:30.437Z - info: [ui] launching: 2.9.0 (Mac OS 12.0.0)
2021-08-25T10:56:30.437Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2021-08-25T10:56:30.995Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.644s)

```

**Comment by sergiou87** [comment]
Weird… Have you tried to uninstall it entirely? I wonder if moving the app around and all that could have broken something.

I definitely wouldn't expect you to give it any special permissions either 🤔

**Comment by ckizer** [comment]
Yes, I've completely removed the app all the preferences, and it still continues to do this even with the latest version. It's not just me. My coworkers are having the same issue. 

**MacOS Monterey 12.1 (21C52)**

![ScreenShot 2021-12-20 at 18 59 15@2x](https://user-images.githubusercontent.com/191738/146848375-73d1cf7d-0564-40a8-8552-64ec44622ae8.png)

<img width="1072" alt="ScreenShot 2021-12-20 at 19 00 00@2x" src="https://user-images.githubusercontent.com/191738/146848402-ea039997-e68b-4334-b4a0-ddda60c2991a.png">

Clicking "Quit and install Update" just quits the GitHub app and never relaunches. This has been ongoing for 2+ years on multiple machines, as well as several coworkers with a similar issue who work out of remote offices, and have completely different Ones and aren't on the same network, or have any corporate VPN blocking anything.

**Comment by sergiou87** [comment]
Just to make sure I understand: "Quit and install Update" never relaunches the app, but when you open it again manually… is it updated or is still prompting you to update?

**Comment by ckizer** [comment]
> Just to make sure I understand: "Quit and install Update" never relaunches the app, but when you open it again manually… is it updated or is still prompting you to update?

YES

**Comment by niik** [comment]
Hey @ckizer, sorry but just so that we're clear, after opening it manually is it **updated** to the latest version or is **still prompting** you to update?

**Comment by dxdc** [comment]
I've had this issue for *years* now myself. See #11705 and several others I'm sure you can find.

@ckizer's comment piqued my curiosity, and I had similar entries in my stderr file.

Then, I deleted this folder: `~/Library/Caches/com.github.GitHubClient.ShipIt`. There's nothing important inside of it, it seems like just a new version of Github Desktop, and a few benign log/plist files related to the update.

Afterwards, I opened up Github Desktop, and the update / restart worked perfectly!

There are some new entries in the stderr file, which indicate a new version of ShipIt may have been installed. I am curious, does this work for anyone else?

~~I'm also wondering if the presence of the stderr file may prevent future updates (i.e., if that was the initial problem). We'll have to wait and see on that one.~~ **Update**: The latest update worked as expected, it seems deleting this folder really may have solved the problem.

```
2022-02-21 07:49:37.084 ShipIt[60327:19419449] On main thread and launching: file:///Applications/GitHub%20Desktop.app/
2022-02-21 07:49:37.084 ShipIt[60327:19419449] Bundle URL is valid
2022-02-21 07:49:37.084 ShipIt[60327:19419449] Attempting to launch app on 11.0 or higher
2022-02-21 07:49:37.084 ShipIt[60327:19419449] Launching new ShipIt at /Applications/GitHub Desktop.app/Contents/Frameworks/Squirrel.framework/Resources/ShipIt with instructions to launch file:///Applications/GitHub%20Desktop.app/
2022-02-21 07:49:37.085 ShipIt[60327:19419260] Installation completed successfully
2022-02-21 07:49:38.451 ShipIt[60355:19419573] Detected this as a launch request
2022-02-21 07:49:38.513 ShipIt[60355:19419573] Successfully launched application at file:///Applications/GitHub%20Desktop.app/
2022-02-21 07:49:38.513 ShipIt[60355:19419573] ShipIt quitting
2022-02-21 07:49:38.514 ShipIt[60327:19419449] New ShipIt exited
2022-02-21 07:49:38.515 ShipIt[60327:19419449] ShipIt quitting
```

**Comment by dxdc** [comment]
The latest update / restart worked. That being said, there's definitely something that needs to be debugged as far as the update process. I am seeing these errors in the ShipIt `stderr` log now, still with a blank `stdout` log.

```
2022-02-25 05:02:03.414 ShipIt[2476:23485918] Detected this as an install request
2022-02-25 07:56:06.069 ShipIt[2476:23632097] Beginning installation
2022-02-25 07:56:07.906 ShipIt[2476:23617792] Moved bundle from file:///Applications/GitHub%20Desktop.app/ to file:///var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/com.github.GitHubClient.ShipIt.EfgAYzhX/GitHub%20Desktop.app
2022-02-25 07:56:07.906 ShipIt[2476:23617792] Moved bundle from file:///var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/com.github.GitHubClient.ShipIt.eaWwBFmP/GitHub%20Desktop.app to file:///Applications/GitHub%20Desktop.app/
2022-02-25 07:56:08.192 ShipIt[2476:23617792] Couldn't remove owned bundle at location file:///var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/com.github.GitHubClient.ShipIt.eaWwBFmP/GitHub%20Desktop.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“GitHub Desktop.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/rv/spd1m5_524j35pnylts_bxvm0000gn/T/com.github.GitHubClient.ShipIt.eaWwBFmP/GitHub Desktop.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2022-02-25 07:56:08.492 ShipIt[2476:23632133] On main thread and launching: file:///Applications/GitHub%20Desktop.app/
2022-02-25 07:56:08.492 ShipIt[2476:23632133] Bundle URL is valid
2022-02-25 07:56:08.492 ShipIt[2476:23632133] Attempting to launch app on 11.0 or higher
2022-02-25 07:56:08.492 ShipIt[2476:23632133] Launching new ShipIt at /Applications/GitHub Desktop.app/Contents/Frameworks/Squirrel.framework/Resources/ShipIt with instructions to launch file:///Applications/GitHub%20Desktop.app/
2022-02-25 07:56:08.493 ShipIt[2476:23617792] Installation completed successfully
2022-02-25 07:56:09.861 ShipIt[7045:23632208] Detected this as a launch request
2022-02-25 07:56:09.921 ShipIt[7045:23632208] Successfully launched application at file:///Applications/GitHub%20Desktop.app/
2022-02-25 07:56:09.921 ShipIt[7045:23632208] ShipIt quitting
2022-02-25 07:56:09.923 ShipIt[2476:23632133] New ShipIt exited
2022-02-25 07:56:09.923 ShipIt[2476:23632133] ShipIt quitting
```

**Comment by bshimel** [comment]
@dxdc, I tried removing `~/Library/Caches/com.github.GitHubClient.ShipIt` and, so far, it seems to have fixed the issue. I will report back if the problem reoccurs. Thanks!

**Comment by IgnacioBecerra** [comment]
@bshimel I've been having this problem for so long, can't believe this finally worked, thanks!

**Comment by sergiou87** [comment]
If it happens again, please share the contents of that folder so we can understand better what the problem is! Also thank you for sharing the solution @dxdc 🙇‍♂️
