### ISSUE TITLE
Fullscreen crosses the monitor edge

### ISSUE THREAD

**Issue by Romz24** [desktop/desktop#13939]
### Describe the bug
Full screen GitHub desktop with a multi monitor setup results in a small white line on the other window. The relative positions of the monitor doesn't matter, thus having primary left/right has the same behaviour. Below the screenshot of the edge of a all monitor screenshot.

### Version & OS

App Version: **2.9.9 (x64)**

OS Name: **Windows 10 Pro**
OS Version: **21H2**

### Steps to reproduce the behavior

1. Need to have multiple monitors
2. Open any application on the primary window
3. Open GitHub desktop full screen on the secondary window
4. Bugs appears at the monitor edge on the primary window, small white line
5. Switching to the other application 'removes'/'hides' the white line

### Expected behavior

Do not cross the border of the monitor on full screen

### Actual behavior

A few pixels over the edge of the monitor

### Screenshots

<details>
<summary>Screenshots</summary>

![bug1](https://user-images.githubusercontent.com/2458113/154617556-becb45a5-a700-49fd-b91d-e4941d21f171.jpg)

</details>

### Additional context

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/2458113/154617833-a0aaf523-2312-452a-a4fe-97f480970e58.png)

</details>

Monitor Resolution: 1920x1080

**Comment by sergiou87** [comment]
Thanks for your report @Romz24 ! ❤️ 

Is this something new that started happening with 2.9.9 or did it happen with previous versions too?

**Comment by Romz24** [comment]
This happened to me recently, before the updates I did not see this.

**Comment by leongersen** [comment]
FYI, this was also reported in #1497, #10267 and #14017.

**Comment by samuelT2** [comment]
> FYI, this was also reported in #1497, #10267 and #14017.

#1497 and #10267 must have been fixed in the meantime. That annoying white pixel stripe on my secondary screen only popped up recently and I'm using Github Desktop since a longer time. I agree with #14017, that's the same bug as reported here.

**Comment by samuelT2** [comment]
Btw, this is how it looks like (at least on my screen).

![IMG_8851](https://user-images.githubusercontent.com/10983143/158202527-70fb673c-908b-48a8-835a-1c6375a11558.jpg)

**Comment by Romz24** [comment]
Version 2.9.11 (x64)

The problem is still there

**Comment by pikawika** [comment]
Issue still persists on Version 3.0.0 (x64).

Overflows independent of monitor or resolution used (1080P monitors and QHD in my tripple monitor setup overflow in same manner as shown by @samuelT2)

W10 pro 64 bit
Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
GTX 970 4GB
16 GB Ram

**Comment by vsergeenko777** [comment]
Issue with white lines is still relevant even on version 3.0.0. I tried older versions: 2.9.8 - no lines and 2.9.9 - have lines.

Detailed examination shows that the issue appeared in [this](https://github.com/desktop/desktop/commit/ec4eabeded495cda1e4d3ab7612b7035487e1da1) commit. Reverting commit solves the issue and the white lines do not appear.

**Comment by samuelT2** [comment]
Still there with v3.0.1. Is it possible to raise the priority a level? At least for me, that white pixel border freaks me out, especially when it's dark in the room :).

**Comment by sergiou87** [comment]
@samuelT2 the problem is this bug comes from Electron, and upgrading Electron might introduce new regressions (like this one… or much worse 😕 we **had** to upgrade from Electron 11 to the current Electron 17 because we kept running into multiple much worse issues in Electron 12, 13, 14, 15 and 16).

We'll probably need to upgrade Electron in the upcoming months anyway, since the Electron team will drop support for v17 in the upcoming months. Stay tuned 🤞

**Comment by sergiou87** [comment]
Closing this as it will be finally fixed with the Electron upgrade to v19 in 3.0.8. See https://github.com/desktop/desktop/pull/15239
