### ISSUE TITLE
persistent login requests - does not stay logged in

### ISSUE THREAD

**Issue by bmrazik-pl** [desktop/desktop#15163]
### The problem

since the latest update, i am prompted to sign in online, use my token, etc - i do (either way), and it prompts again at a later time - this did not happen before

### Release version

3.0.6

### Operating system

windows 10

### Steps to reproduce the behavior

1. open github desktop
2. wait
3. when prompted sign in via browser or token
4. wait
5. get prompted again
6. repeat steps 3-5

### Log files

[2022-08-24.desktop.production.log](https://github.com/desktop/desktop/files/9417501/2022-08-24.desktop.production.log)

### Additional context

was ready to move to new version as last version stopped working on the create pr and was hoping this would have the fix

**Comment by sergiou87** [comment]
That's weird 🤔 

How do you get prompted to sign in? Is it some kind of error? Could you post screenshots of the process?

**Comment by bmrazik-pl** [comment]
Clicked to refresh from origin…got this

***@***.***

Chose token, entered my token…was able to fetch….

Clicked fetch again and got same image as above…
Chose sign in w/ browser….
***@***.***

In the browser

Fyi, until I do this it does not allow fetch/push, etc….

**Comment by steveward** [comment]
@bmrazik-pl screenshots don't come through in email replies, so if you have screenshots of the errors you encountered you will need to upload them directly to this issue. Thanks!

**Comment by bmrazik-pl** [comment]
![image](https://user-images.githubusercontent.com/26815777/186499736-adab6a40-6dfa-4fa9-b2e2-664f60816e12.png)

![image](https://user-images.githubusercontent.com/26815777/186499831-0155217a-ad3b-4ff2-9ab7-6dcb325e2ebc.png)

**Comment by steveward** [comment]
@bmrazik-pl that looks like the authentication dialog for the command line version of Git, not GitHub Desktop. I'm not sure why you're hitting that dialog from GitHub Desktop, unless you have a hook that's triggering it. 

The log file from GitHub Desktop indicates you have an active authentication session -- can you try cloning a private repository directly from Desktop to see if that succeeds?

**Comment by bmrazik-pl** [comment]
It allows me to clone a local from w/in desktop – I’ve made no changes to desktop config itself when I go to publish the test branch, I get the same popup for authentication

**Comment by bmrazik-pl** [comment]
it regularly occurs when clicking fetch button at top

**Comment by hutch120** [comment]
Just today I updated Github Desktop and started seeing something super similar. When I checked in some code and syncd to a private Github repo. It pops up a Bitbucket login (I haven't used bitbucket in years and the repo I'm using has nothing to do with Bitbucket.) See attached screenshot.

![image](https://user-images.githubusercontent.com/1034955/186553418-e3890f4f-7069-48ad-aa6c-91e74de5605b.png)

**Comment by ReLater** [comment]
I can confirm the find of @bmrazik-pl with WIN 10.

- In my case: Additionally I have an endlessly spinning "Fetching origin".
- My account settings in "Github Desktop" say that I'm logged in.
- The repo were this happens (spinner) is a private one. Not with public ones as far as I see.
- Never had this behavior before last update,
- When I switch to another private repo. Login popup comes up and afterwards endlessly spinning "Fetching origin".
- I can "Commit to main" locally. But not "Push Origin". 
- Have to close "Github Desktop", open it newly, and can "Push Origin" once. Spinner starts again.
- I used now https://github.com/login/device and all works FOR THE MOMENT. But I don't like this method ;-)

**Comment by sergiou87** [comment]
@ReLater @hutch120 do you know which specific repository is showing that dialog to you? **It might not be the repository you're in, but some other from your repository list**.

Once you find out which one is showing the popup, it'd be nice if you could open it from a terminal and run `git symbolic-ref -q refs/remotes/origin/HEAD`. I think that's the command causing the popup (added in #14985 ). If you manage, to show the popup from the terminal running that command, try again running this other one: `git -c credential.helper= symbolic-ref -q refs/remotes/origin/HEAD`

If my theory is correct, that `-c credential.helper=` should fix the problem.

**Comment by ReLater** [comment]
> do you know which specific repository is showing that dialog to you? It might not be the repository you're in, but some other from your repository list.

Any private repo in the left sidebar of GD showed the same bahavior like I described above. When I clicked on a public one, spinning stopped. All fine. When I went back to the last private one spinning goes on there. When I clicked on another private one I could do some steps like described above. Then spinner runs endlessly in this repo, too, and still in the other private one.

**Comment by sergiou87** [comment]
@ReLater @hutch120 you can also try out ~~this test build~~ which adds `-c credential.helper=` to the aforementioned `git` command introduced in #14985 . Please let me know if that fixes the problem 🤞 

**EDIT:** removed the link, this is the right test build: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-test2-1da95508/GitHubDesktopSetup-x64.exe

**Comment by hutch120** [comment]
@sergiou87 Tried to run that command, but nothing popped up (at least not right away). Also clicked fetch and did a check in (successfully), etc, and didn't get the popup.... THEN... a minute or so later, the (Atlassian) login popup occurred (maybe a timeout on something or a background task). Not sure what is causing or how to easily reproduce. I'll install the test build now and see if the issue goes away.

**Comment by hutch120** [comment]
So, bad news, installed the test build (3.0.7-test1) and popup still occurs. Again, doesn't seem to be triggered directly off a user action. At least if it is there is some timeout before it shows up. Also, to be clear, I'm checking into a github repo, not a bitbucket repo.

Could this global config have anything to do with it? I just can't figure out where the link to Atlassian/Bitbucket is.

![image](https://user-images.githubusercontent.com/1034955/186775471-47b02633-2dd2-431f-9e03-1860abe444f9.png)

I only have a Github Account showing here

![image](https://user-images.githubusercontent.com/1034955/186776071-4ca10f0c-1700-4383-a822-94a5f5c9b75a.png)

Note the checkbox for periodically checking.. seems like possible behaviour I'm seeing.

![image](https://user-images.githubusercontent.com/1034955/186776214-aa267386-e06c-4ec6-826a-2162b08ff1f7.png)

**Comment by cicirello** [comment]
I started having same problem yesterday on Windows 10. Definitely authenticated. If I simply close the random login boxes, GitHub Desktop works fine including pushing. Get random login box again later.

**Comment by sergiou87** [comment]
I'm sorry @hutch120 , I made the change in the wrong git command (it's not `symbolic-ref` the one doing the network call, but `remote set-head`).

This one should contain the proper fix: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-test2-1da95508/GitHubDesktopSetup-x64.exe 🤞

**Comment by sergiou87** [comment]
Please @cicirello try the test build mentioned in my previous comment and let me know if it helps 🤞

**Comment by hutch120** [comment]
Installed.... it is the weekend here... looks ok so far. Will get back to you next week.

**Comment by bmrazik-pl** [comment]
Will this work for my issue as well? (asking as you’ve mentioned others in particular)

**Comment by sergiou87** [comment]
@bmrazik-pl Yes! I think it's the same, sorry I didn't mention you 😳

**Comment by bmrazik-pl** [comment]
No worries….just making sure 😊 – I’ve installed and so far so good – will post if anything comes up – thank you

**Comment by photonstorm** [comment]
Just to confirm, this happens on Windows 11 as well. I get the same **GitHub Sign in** window appear (at least a minute or two after opening GitHub Desktop), but even if I close it, not signing in, GitHub Desktop continues to work fine anyway. Only started happening with the  3.0.6 (x64) release, doesn't happen for me on macOS.

Have just installed 3.0.6-beta.3 and will see what happens with this version.

**Comment by sergiou87** [comment]
@photonstorm please try build 3.0.7-test2 instead (download it from https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-test2-1da95508/GitHubDesktopSetup-x64.exe) which is the one that hopefully contains the fix 🤞

**Comment by photonstorm** [comment]
@sergiou87 just installed 3.0.7-test2 and so far, no prompt has appeared. Will carry on testing for the rest of the day.

**Comment by cicirello** [comment]
@sergiou87 it seems to have resolved itself before I had the chance to install the test version. Here's a little more detail of my experience. All day Wednesday, I was getting the random login prompts periodically from the Git Credential Manager. I simply dismissed them that day, without any effect on my ability to push, etc. On Thursday morning, the first time I encountered it, I actually did log in successfully, but then continued to get the login box periodically throughout the day, and just dismissed it the rest of the times without any ill-effect (just like the day before). So far today, I haven't been prompted at all. Very strange.

**Comment by abraunegg** [comment]
@sergiou87 
Still experiencing this with 'Version 3.0.6 (x64)' ... when will the fixed version be available ?

**Comment by sergiou87** [comment]
@abraunegg please try build 3.0.7-test2 (download it from https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-test2-1da95508/GitHubDesktopSetup-x64.exe) which is the one that hopefully contains the fix and let me know if it works for you🤞

Once we know the fix works, we'll release a version with the fix ASAP (maybe on Tuesday?)

**Comment by photonstorm** [comment]
Test2 seemed to solve it for me. Will continue testing all Monday but so far, so good.

**Comment by hutch120** [comment]
Not seeing today. Thanks for quick fix!!

**Comment by bmrazik-pl** [comment]
@sergiou87 i have not had any issues since your patch was installed

**Comment by sergiou87** [comment]
In case anyone is interested, we intend to release v3.0.7 with the fix tomorrow (see #15193). If anyone prefers to have a fix today, we just deployed v3.0.7-beta1 (see #15194) that you can download from https://desktop.github.com/beta

Thank you all for your patience and help with this issue! 🙇‍♂️

**Comment by photonstorm** [comment]
@sergiou87 given I've currently got test2 installed, do I just have to download and re-install the release version to get rid of the beta/test and go back to stable?

**Comment by sergiou87** [comment]
@photonstorm I'll ping you here when the new production build is out, as you will need to install it again from desktop.github.com

Sorry about that!

**Comment by sergiou87** [comment]
Hi all! We just released 3.0.7 with the fix a few hours ago.

> **Warning**
> If you have installed either the latest beta or one of the test builds I shared (3.0.7-test1 and 3.0.7-test2), **DO NOT** install 3.0.7 unless you don't mind losing your repositories on GitHub Desktop and re-adding them there. They **won't** be removed from your local disk, don't worry about that, they're just removed from the **repository list** inside of GitHub Desktop. This is because those beta and test builds use [Electron](https://electronjs.org) v19, while the latest 3.0.7 has Electron v17 and won't be able to open the repository database once it's been migrated to Electron v19.
>
> We will release a new production build soon with Electron v19 that you can update to. I will let you know again when that happens.

If ☝️ this ☝️ warning doesn't affect you, or you don't mind re-adding all your repos to GitHub Desktop, you can update immediately from the About dialog. If it doesn't find a release (**it's not enabled to _all_ users yet**), try hold <kbd>Alt</kbd> on your keyboard and then click on the `Ensure Last Version` button to force the upgrade:

https://user-images.githubusercontent.com/1083228/187416390-01ee032d-8dca-4635-ab0e-a3c4c87e4c5d.mov

You can also download it from https://desktop.github.com

Thank you for your patience!! 🙇‍♂️

**Comment by photonstorm** [comment]
Yikes! I'm glad I read this warning first - I really don't want to re-add all my repos!

Will wait for the new production release on Electron v19 I guess.

**Comment by sergiou87** [comment]
@photonstorm as promised, now you can go back to production builds downloading the app again from https://desktop.github.com/

It contains Electron v19 so your repositories will persist (you can backup `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop` if you still want to be extra cautious… that folder contains your settings and the list of repos).

Thanks for your patience and sorry for the inconveniences we caused 🙇‍♂️

**Comment by photonstorm** [comment]
@sergiou87 awesome,  thanks for the ping. I've installed 3.0.8 stable, and all good so far :)

It did occur to me that it'd be awesome if GitHub Desktop had a way to back up all of its user data to one of my GitHub repos :)

**Comment by hmcmann65** [comment]
> @sergiou87 awesome, thanks for the ping. I've installed 3.0.8 stable, and all good so far :)
> 
> It did occur to me that it'd be awesome if GitHub Desktop had a way to back up all of its user data to one of my GitHub repos :)

**Comment by justingolden21** [comment]
I've used Desktop for many many years and never had this. Now I get a prompt to sign in about every 3 minutes. The program is completely unusable. Latest version, Windows 11. Might need to file a new issue.
