### ISSUE TITLE
Reduce the pain of consuming SSH remotes

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2579]
There's a collection of issues spread across multiple issues which touch on situations involving SSH remotes:

 - a user isn't clear on how to setup their machine to consume SSH repositories: #2453 #2847

> I looked around, and I cannot see anywhere, either in the desktop app settings, nor in the settings for any repository, nor in my GitHub profile settings, where I would go about doing SSH remote configuration.

- cloning a repo via SSH (and not defaulting back to https) - #2085 

 - setting up an SSH key and registering it on GitHub on behalf of a user - #2577

 - a repository with SSH submodules cannot be cloned because of a vague authentication failure: #2344 #2338

 - an SSH private may be protected with a passphrase - this can be handled by `ssh-agent` or PuTTY #2859

 - No way to trust unknown host keys - #3457 

- Using plink causes pushes to hang - #8765 

- No option for a default protocol (https://github.com/desktop/desktop/issues/11885)

- No support for hardware keys (https://github.com/desktop/desktop/issues/12216) 

- Desktop does not use OpenSSH on Windows if running, favours embedded SSH (#5641)

The classic apps addressed some of this (at least on the Windows side):

 - creating a new SSH key if not found and adding it to GitHub
 - ensuring `ssh-agent` was running when launching the app or Git Shell
 - setting the right environment variables when performing Git operations

**Comment by joshaber** [comment]
The Classic Mac app did essentially the same as Windows, minus the `ssh-agent` stuff since that was unnecessary.

**Comment by mcmonkey4eva** [comment]
Does current GitHub Desktop support SSH remotes at all?
I ran ssh-agent, did ssh-add on my keys (all on a random git bash instance) and it was all successful.
Github Desktop then failed to fetch or pull an SSH repo.
For reference, old Github-Windows client pulls the same fine.

Fair note that I've never use ssh-agent manually before, so I may have messed up somewhere.

So two things:

- Full support for making this easy and automated in the new Desktop client.
- How would I set it up under current limitations to where I can pull SSH repos in the new Desktop client?

**Comment by shiftkey** [comment]
> How would I set it up under current limitations to where I can pull SSH repos in the new Desktop client?

@mcmonkey4eva I ran through [this guide](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) again using the latest version of Desktop, and I was able to push changes to an SSH remote using Desktop. Maybe ensure you do `eval $(ssh-agent -s)` before launching Desktop as this will environment variables that are important to Git.

**Comment by mcmonkey4eva** [comment]
I'm fairly sure SSH Agent is running fine.
Evidence for this is that the command line will pull the repo happily.
Desktop was started in first testing before the SSH Agent config, and later started after, as well as restarted past that point a few times. At no point was it able to pull.
I'm using a standard Git Bash (right click desktop -> `Git Bash Here`) to open the SSH Agent.
I've carefully ensured as well that there's never been more than one SSH Agent running at the same time. (Just launching the SSH Agent a second time will duplicate it normally)

**Comment by shiftkey** [comment]
@mcmonkey4eva a thought: is there something interesting with your SSH key - does it have a passphrase associated with it?

**Comment by mcmonkey4eva** [comment]
Nope! Standard old-github-desktop autogenerated SSH key, whose pub file was uploaded to an unrelated git server.

**Comment by strafe** [comment]
Does this work with Pageant/Plink?

With my current configuration I can use Git Bash directly to pull and push changes to a private gitlab repository, whereas with GitHub Desktop even after setting my Shell to Git Bash I can not perform those operations on the same repository.
`Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.`

**Comment by shiftkey** [comment]
@mcmonkey4eva 

> Standard old-github-desktop autogenerated SSH key

Was it named `github_rsa` by any chance? That might be the issue - I've got a similar report of this which was fixed by renaming it to `id_rsa`.

**Comment by mcmonkey4eva** [comment]
It was yes .-.
Thanks for the info!

**Comment by thenetimp** [comment]
Better error messages would be nice.  For example on MacOS High Sierra if you don't use ssh-add to add your key because you are using a passphrase on your ssh key then github desktop throws a generic message of 

"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository."

If this message had been more specific, it wouldn't have taken me 30 minutes to figure out what was going on....

**Comment by niik** [comment]
Added link to #3457 in the body

**Comment by nanomebia** [comment]
it's probably a good idea to add in functionality to specify which key the desktop client will use by default (and also per-repo if people don't want to configure it via an ~/.ssh/config file) as users may have different keys for different repos/work domains/other domains

**Comment by cicorias** [comment]
Can an option be added when I click on the `use desktop` from the GitHub repo "clone" action that says "Use ssh - ONLY IF YOU KNOW WHAT YOU"RE DOING"...

Just a pain.  I love the "just click clone" flow for checking things out. But to push I have to update the origin via `git remote set-url...` command - or use the Desktop settings and just paste it in.  Minor but I look a a lot of code..

**Comment by chrisrapson** [comment]
@thenetimp (or anyone else) I don't suppose you know the workaround for github desktop refusing to push using a password protected ssh key in windows do you? When I run `ssh-add` in gitbash, I get `Could not open a connection to your authentication agent.`

**Comment by mcmonkey4eva** [comment]
@chrisrapson you have to do `eval $(ssh-agent -s)` first to start up the ssh agent - GitHub Desktop currently will not make use of it, but you can start it up, then use the `ssh-add`, then pull/push within the git bash terminal.

**Comment by chrisrapson** [comment]
oh, I didn't have any problems doing `git push` from gitbash. I was hoping there was a way to make it work from GitHub Desktop. All it needs to do is pop up a password prompt. If I'm understanding correctly, that's not possible at the moment? Should I open a new issue?

**Comment by pedrohudson-hotmart** [comment]
So basically, you can't use GitHub Desktop with SSH remote?

**Comment by muratbalci-ingame** [comment]
cmd works github desktop doesnt. what? ._.

**Comment by tamoyal** [comment]
Any suggestion for getting this working with AWS Code Commit repos? Btw, [Fork](https://git-fork.com/) just works

**Comment by tnorthcutt** [comment]
@shiftkey are there any guidelines/docs somewhere on how to resolve this issue? I'm on a Mac, and for the life of me I cannot push with the desktop app. I can via CLI just fine, however.

**Comment by mcmonkey4eva** [comment]
@tnorthcutt (and anyone else scrolling to the bottom here confused) I can't speak for OS's other than Windows, but having an `id_rsa` SSH key (ie the default key name) seems to work fine for pull/push within current versions of GitHub Desktop, as shiftkey mentioned in an earlier post.

**Comment by tnorthcutt** [comment]
@mcmonkey4eva Thanks for the suggestion.

I was able to get this working by adding the following to my `~/.ssh/config` file:
```
Host *
	AddKeysToAgent yes
	UseKeyChain yes
	IdentityFile ~/.ssh/id_rsa
```

**Comment by IncludeSec** [comment]
This issue has caused some serious annoyance for us with the GUI. An entire clone fails with a generic "authentication error" if there is a public github based submodule linked within a private repo. The GUI should auto-add an SSH key like the classic app used to do. Or perhaps the windows client can stop requiring a key for cloning of a public repo?

However you fix it, I hope you do! Thanks :)

**Comment by steveward** [comment]
Feedback from #8443 

>Allow to always use SSH for remote urls (including upstream).
>
>Right now, GitHub Desktop uses https urls by default, which is annoying since it requests credentials from the terminal on each usage (and also breaks automation for things like publishing scripts). I have to set the url back to an ssh one every time I clone a new repo from GitHub Desktop, resulting in systemic loss of time.

**Comment by steveward** [comment]
Feedback from https://github.com/desktop/desktop/issues/8761 about working with SSH keys with passphrases:

>When we followed the instructions for setting up SSH keys, that involves making a passphrase. Then when we started using Github desktop, it will not clone or pull the repos. It gives error message about authentication failure. It suggested logging in again and that didn't help. It seems like the desktop app does not prompt for SSH key passphrase when it should.

**Comment by mcmonkey4eva** [comment]
@steveward I believe you unintentionally closed this issue while intending to just post a comment?

**Comment by pboling** [comment]
Every time I setup a new machine I download Github Desktop, hoping this bug will have been fixed.  Every time I discover that it has not been, throw it away, and vow to check back in a few months.

The app is nigh useless with a default setting of HTTP.  Life is annoying enough already.

How is this not a configurable option?

**Comment by alexandre-liberato** [comment]
I've been trying to understand why Github Desktop didn't work with SSH and after doing a test, I realized that Git Bash works perfectly with SSH keys, BUT Gitbub Desktop only works if the repository is configured as HTTP . That is:

Git Bash works with

> git@github.com:alexandre-liberato/project-curso-git.git

and with

> https://github.com/alexandre-liberato/projeto-curso-git.git

BUT Github Desktop ONLY WORKS with

> https://github.com/alexandre-liberato/projeto-curso-git.git

**Question**: Does anyone know how to configure both separately so that Git Bash uses SSH and Github Desktop uses HTTP?

**Comment by hani77979** [comment]
B

**Comment by dougbreaux** [comment]
@alexandre-liberato I also discovered that if I launch GitHub Desktop from Git Bash, it works with SSH as well.

**Comment by alexandre-liberato** [comment]
> 
> 
> @alexandre-liberato I also discovered that if I launch GitHub Desktop from Git Bash, it works with SSH as well. At least with my corporate GitHub Enterprise instance.

I tried to launch Github Desktop from Git Bash, but the SSH still not working as expected. I am not on a Github Enterprise account.

**Comment by vytautas-pranskunas-** [comment]
watching

**Comment by RangelReale** [comment]
Using Windows and Putty, if I set this environment variable I can use SSH with Desktop without problems
```
GIT_SSH=c:\Program Files\PuTTY\plink.exe
```
Only thing missing is cloning using ssh. If I clone with another program, ssh works fine.

**Comment by h8nor** [comment]
It's amazing in **Github Desktop x32** of latest version `ssh-agent` has always been launched, which could be checked by the command **`ssh-add -l`**. Terminal and Github Desktop easily picked up `ssh-agent`.

After **Github Desktop x64** necessary to install the **git** with terminal separately (it has a useless script *`start-ssh-agent.cmd`* for Windows) and [indicate the path to it](https://github.com/desktop/desktop/issues/5454 "%ProgramFiles%\Git\cmd"). Terminal works only, the app doesn't react at all. To work in terminal needs script **`~/.profile`** that `ssh-agent` closes along with terminal.
``` bash
SSHAGENT=/usr/bin/ssh-agent
SSHID=~/.ssh/id_rsa

proc=$(git config --get remote.origin.url)
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ] && [ "${proc::4}" != "http" ]; then
	eval $(ssh-agent -a ~/.ssh-agent.$$) && ssh-add "$SSHID"
	trap "kill $SSH_AGENT_PID" 0
fi
unset SSHID SSHAGENT
```
There are comments *pass is stored in an open form*, so no longer saved (including Windows).
If so OpenSSH_8.x is an isolated app, Githab Desktop will not be able to work with ssh.

**Comment by EasyArray** [comment]
I'm trying to use GitHub Desktop with a repository on a server at my university. This server does not have an https url (so I need ssh) but it also does not allow key authentication. You have to enter a password every time you ssh there. Is there any way to set up GitHub Desktop to work with this repository? Thanks!

**Comment by steveward** [comment]
Thanks to the work of @sergiou87 we'll be shipping improved SSH support in GitHub Desktop. We would love for anyone in this thread who was encountering SSH issues to test it out by installing the [Windows beta version]( https://github.com/desktop/desktop#beta-channel). Let us know if you run into problems!

**Comment by hardysim** [comment]
I've tried the current windows beta (2.9.1-beta4 x64) and it ask for the ssh key password right when opening it (and I checked the "save password" checkbox). But when trying to fetch something, I get the usual "Authentication failed" error dialog. I've tried using "system OpenSSH" in the settings but neither with or without it I get the same error.

**Comment by sergiou87** [comment]
@hardysim thank you for your feedback! Could you share your logs with me after getting that error so I can see why exactly?

**Comment by hardysim** [comment]
Sure:

```
2021-08-18T08:11:49.213Z - info: [ui] [AppStore] loading 1 repositories from store
2021-08-18T08:11:49.214Z - info: [ui] [AppStore] found account: shardt (Simon Hardt)
2021-08-18T08:11:49.488Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-08-18T08:11:49.509Z - info: [ui] launching: 2.9.1-beta4 (Windows 10.0.19043)
2021-08-18T08:11:49.511Z - info: [ui] execPath: 'C:\Users\Simon\AppData\Local\GitHubDesktop\app-2.9.1-beta4\GitHubDesktop.exe'
2021-08-18T08:12:00.851Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: android-ecare - shardt (has token)
2021-08-18T08:12:01.614Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git@github.xyz.net: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
```

I have a feeling that it does not use the ssh key at all. I've removed GitHub Desktop and reinstalled but it did not ask for the ssh key password again.

**Comment by sergiou87** [comment]
> it did not ask for the ssh key password again

That's because the key password is stored in the credentials manager. I wonder… is it possible you entered the *wrong* password for the SSH key? I just realized we're not handling that scenario properly, and the wrong password might be kept 🤦‍♂️ 

I'll look into that, meanwhile you can open the Credential Manager on Windows, and on Windows Credentials, look for `GitHub - SSH key passphrases` and delete that entry. The app should prompt you the key password again.

**Comment by hardysim** [comment]
Ahh here we go. Yes, it was wrong. After removing it from windows GitHub Desktop asks for it again and using the correct password, it fetches just fine. So please add a better handling when saving a wrong password and we're good to go.

**Comment by sergiou87** [comment]
@hardysim we have improved that behavior in #12800 and now it should only store good passwords. Those improvements are available in the latest beta 2.9.1-beta6

However, beware, we found an edge case where a certain combination of “remember passphrase” and “don’t remember passphrase” + bad password and good password, could cause the bad password to be stored. I'll tackle that one tomorrow!

Thank you again for your feedback! ❤️ 🙇‍♂️

**Comment by sergiou87** [comment]
This should be much better now with the release of GitHub Desktop 2.9.1 today 😄 

Therefore, we decided to close this issue and start again with new issues found in its current state.

Thanks everyone for your help and patience! ❤️

**Comment by ajtruckle** [comment]
I am completely and utterly confused.

- I created keys manually.
- I created keys with PuttyGen.
- I converted to PPK.
- I added to Putty Pageant.

In each case the files are no own names and in my own directories and with passphrase.

- I added the public key to my GitHub settings.
- I try to sync with GitHub desktop - says I am not signed in even though I am. 
 
I have to use the HTTPS route.

Why? Please help. Confused out my mind.

**Comment by steveward** [comment]
@ajtruckle I would recommend using Git for Windows instead of PuTTY and following the specific steps in this help article to get SSH working:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Make sure `ssh-agent` is running and your key has been added.

**Comment by ajtruckle** [comment]
Hi @steveward Eventually I was given some help on StackOverflow:
https://stackoverflow.com/q/72345710/2287576
As you say, it was easier to move over to using SSH in the settings.
I eventually found out how to add the `ssh-agent` service and configure.
