### ISSUE TITLE
"No editors found" even though Atom is installed

### ISSUE THREAD

**Issue by mberasategi** [desktop/desktop#2585]
### Description

I just insalled GitHub Desktop and Atom, and when I try to set up Atom as de default external editor for Github Desktop it says "No editors found". I tries uninstalling and then installing Atom first, with no success. 

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** MS Windows 6.1.7601

### Steps to Reproduce

1. Installed both GitHub Desktop and Atom
1. On GitHub Desktop, File > Options > Advanced
1. For "External editor" it says "No editors found. Install Atom?" even though Atom is installed and running properly.

### Logs

I don't think there is anything relevant here, but still, latest log:

```
2017-08-30T07:27:23.899Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-08-30T07:27:25.500Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: Se han producido uno o varios errores. ---> System.Exception: Couldn't acquire lock, is another instance running
   en Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   en Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   en System.Threading.Tasks.Task`1.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- Fin del seguimiento de la pila de la excepci�n interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en Squirrel.Update.Program.executeCommandLine(String[] args)
   en Squirrel.Update.Program.main(String[] args)
   en Squirrel.Update.Program.Main(String[] args)
---> (N� de excepci�n interna 0) System.Exception: Couldn't acquire lock, is another instance running
   en Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   en Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   en System.Threading.Tasks.Task`1.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Fin del seguimiento de la pila de la ubicaci�n anterior donde se produjo la excepci�n ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.Update.Program.<Download>d__7.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\[myusername]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.download (C:\Users\[myusername]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21)
    at C:\Users\[myusername]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14
    at ChildProcess.<anonymous> (C:\Users\[myusername]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2017-08-30T07:28:53.184Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 2.032s)
2017-08-30T07:50:49.383Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 1.390s)
2017-08-30T08:02:58.762Z - info: [ui] Opt in reported.
2017-08-30T08:02:59.463Z - info: [ui] Stats reported.
2017-08-30T08:06:05.988Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-08-30T08:18:51.499Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 6.442s)
2017-08-30T08:24:56.861Z - info: [ui] Executing getConfigValueInPath: git config -z --global user.name (took 1.306s)

```

**Comment by shiftkey** [comment]
@mberasategi thanks for the details. Can you tell me about how you have Atom installed? 

We probe this registry key to find the install location: `HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom`. Maybe I'm missing one of the installer options that Atom supports?

**Comment by mberasategi** [comment]
Thanks for your reply @shiftkey . I just downloaded the installer from https://atom.io/ (64bit version) and run it. Install location as found in the registry key you mention is `C:\Users\[myusername]\AppData\Local\atom`.

**Comment by DRSAgile** [comment]
Same issue; the registry entry for Atom is filled properly.

The "InstallLocation" key has "C:\Users\[myusername]\AppData\Local\atom" has value.

When it is still not fixed, can I force the connection with Atom "manually" in any other way?

Also, can I connect it to Notepad++ instead of Atom if I chose so (also "manually" as the application itself does not offer such possibility with GUI)?

**Comment by shiftkey** [comment]
@mberasategi @DRSAgile The next thing to check alongside the registry entry is that the installation is unpacked as expected. Could you check that Atom added itself to your PATH and that the `cmd` file exists (I'm just running these commands in a Command Prompt shell):

```
C:\Users\shiftkey>echo %PATH%
// other entries
C:\Users\shiftkey\AppData\Local\GitHubDesktop\bin;C:\Users\shiftkey\AppData\Local\atom\bin

C:\Users\shiftkey>dir %LOCALAPPDATA%\atom\bin
 Volume in drive C has no label.
 Volume Serial Number is 1073-2740

 Directory of C:\Users\shiftkey\AppData\Local\atom\bin

09/03/2017  12:12 PM    <DIR>          .
09/03/2017  12:12 PM    <DIR>          ..
09/03/2017  12:12 PM                68 apm
09/03/2017  12:12 PM                65 apm.cmd
09/03/2017  12:12 PM                75 atom
09/03/2017  12:12 PM                58 atom.cmd
               4 File(s)            266 bytes
               2 Dir(s)  76,747,313,152 bytes free
```

> Also, can I connect it to Notepad++ instead of Atom if I chose so  

@DRSAgile this is not currently supported. See #2487 for that discussion.

**Comment by DRSAgile** [comment]
@shiftkey Thanks for reply.

Yes, the "%PATH%" is updated; the last two entried there are: "C:\Users\[Username]\AppData\Local\GitHubDesktop\bin;C:\Users\[Username]\AppData\Local\atom\bin"

The dir command works also. The only difference is that free space is different (33 805 893 632).
Atom itself works fine. I tried to restart everything, but it did not help either.

Another issue is that I can not find an option to autopush changes to GitHub's server once I press "Commit" -- it is not convenient as I always forget to manually click to "push" at the top. Maybe I simply failed to find this option?

**Comment by mberasategi** [comment]
Hi @shiftkey , it turns out the Atom dir is not added to my path, and `dir %LOCALAPPDATA%\atom\bin` is not found...

**Comment by shiftkey** [comment]
@mberasategi it sounds like something about your installation failed - there might be something in your `%LOCALAPPDATA%\atom\SquirrelSetup.log` that might shed light on what happened, but I think I'd need to send you over to the [Atom issue tracker](https://github.com/atom/atom/issues) for further assistance.

**Comment by mberasategi** [comment]
@shiftkey OK. I'll try reinstalling as said and if it doesn't work I'll go to the [Atom issue tracker](https://github.com/atom/atom/issues). Thanks for your attention.

**Comment by Ben3eeE** [comment]
@mberasategi The bin folder not being created or modified on install is a known issue with the Atom installer /cc: https://github.com/atom/atom/issues/11450

You can try running `atom --squirrel-updated` from within the `%LOCALAPPDATA%\atom` folder. This should create the bin folder.

**Comment by shiftkey** [comment]
@DRSAgile 

> Another issue is that I can not find an option to autopush changes to GitHub's server once I press "Commit" -- it is not convenient as I always forget to manually click to "push" at the top. Maybe I simply failed to find this option?

Please open a fresh issue to talk about this - it's not relevant to the Atom issue we're investigating here.

**Comment by shiftkey** [comment]
@DRSAgile I'm still not 100% sure why we're not detecting the installation. We enumerate the keys at that location to verify it's the app we expect using the Publisher and DisplayName keys, maybe I'm missing some assumption:

https://github.com/desktop/desktop/blob/355f9671860e4777827912ddc6aac44399f5732f/app/src/lib/editors/win32.ts#L74-L75

Could you run this command from a Powershell prompt and attach the output?

```ps
> Get-Item HKCU:\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom
```

This is what it looks like for my 64-bit installation of `1.19.5`:

```


    Hive: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall


Name                           Property
----                           --------
atom                           DisplayIcon          : C:\Users\shiftkey\AppData\Local\atom\app.ico
                               DisplayName          : Atom
                               DisplayVersion       : 1.19.5
                               InstallDate          : 20170905
                               InstallLocation      : C:\Users\shiftkey\AppData\Local\atom
                               Publisher            : GitHub Inc.
                               QuietUninstallString : "C:\Users\shiftkey\AppData\Local\atom\Update.exe" --uninstall -s
                               UninstallString      : "C:\Users\shiftkey\AppData\Local\atom\Update.exe" --uninstall
                               URLUpdateInfo        :
                               EstimatedSize        : 179214
                               NoModify             : 1
                               NoRepair             : 1
                               Language             : 1033
```

**Comment by DRSAgile** [comment]
@shiftkey Thanks for reply.

 It looks like I have the same data, please see below.

Could you please check the source code if it asks for elevation of privileges/permissions to go through the registry? Maybe the code you cited just receives nothing? 

Normally just reading the data from registry should not be an issue, but in my practice I witnessed weird cases where even reading from registry was not possible without certain permissions, especially with UAC-enabled Windows 10. (I am not a professional in this, so this is only my guess.)



____________________________________________________

PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-Item HKCU:\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom


    Hive: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall


Name                           Property
----                           --------
atom                           DisplayIcon          : C:\Users\[Username]\AppData\Local\atom\app.ico
                               DisplayName          : Atom
                               DisplayVersion       : 1.19.5
                               InstallDate          : 20170902
                               InstallLocation      : C:\Users\[Username]\AppData\Local\atom
                               Publisher            : GitHub Inc.
                               QuietUninstallString : "C:\Users\[Username]\AppData\Local\atom\Update.exe" --uninstall
                                -s
                               UninstallString      : "C:\Users\[Username]\AppData\Local\atom\Update.exe" --uninstall
                               URLUpdateInfo        :
                               EstimatedSize        : 179214
                               NoModify             : 1
                               NoRepair             : 1
                               Language             : 1033


PS C:\Windows\System32\WindowsPowerShell\v1.0>

**Comment by shiftkey** [comment]
> Could you please check the source code if it asks for elevation of privileges/permissions to go through the registry? Maybe the code you cited just receives nothing?

The [code](https://github.com/desktop/desktop/blob/355f9671860e4777827912ddc6aac44399f5732f/app/src/lib/registry.ts) for this is invoking `C:\Windows\System32\reg.exe` and parsing that output:

https://github.com/desktop/desktop/blob/355f9671860e4777827912ddc6aac44399f5732f/app/src/lib/registry.ts#L34-L36

You can test this doesn't require additional permissions by invoking it from a plain command prompt:

```
> C:\Windows\system32\reg.exe QUERY HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\atom

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\atom
    DisplayIcon    REG_SZ    C:\Users\shiftkey\AppData\Local\atom\app.ico
    DisplayName    REG_SZ    Atom
    DisplayVersion    REG_SZ    1.19.5
    InstallDate    REG_SZ    20170905
    InstallLocation    REG_SZ    C:\Users\shiftkey\AppData\Local\atom
    Publisher    REG_SZ    GitHub Inc.
    QuietUninstallString    REG_SZ    "C:\Users\shiftkey\AppData\Local\atom\Update.exe" --uninstall -s
    UninstallString    REG_SZ    "C:\Users\shiftkey\AppData\Local\atom\Update.exe" --uninstall
    URLUpdateInfo    REG_SZ
    EstimatedSize    REG_DWORD    0x2bc0e
    NoModify    REG_DWORD    0x1
    NoRepair    REG_DWORD    0x1
    Language    REG_DWORD    0x409
```

There's one note from the [upstream project](https://github.com/fresc81/node-winreg#processing-utf-8-data) that inspired this around the Windows console not handling UTF-8 characters - it's a long shot, but **is there any special characters in your username that we might not be parsing correctly?** You've also not mentioned other editors (VSCode/Sublime) - if they're also installed, but not showing up in the list under **Options** | **Advanced** tab, then it might not be specific to the Atom installation.

**Comment by DRSAgile** [comment]
@shiftkey The command has worked for me fine.  I do not have VSCode/Sublime installed, only Notepad++.

And yes, your guess might be way closer to the truth as my "[Username]" does contain non-ANSI characters. Does this mean that there is a glitch in the standard console/command? 

If understand correctly, MFC redistributable/its TypeScript alternative, if there is such thing, does not provide an alternative way to do this? I am asking because Microsoft is kind of famous for doing the same thing or almost the same thing more than once, and at times it can be helpful.

**Comment by shiftkey** [comment]
> Does this mean that there is a glitch in the standard console/command?

I'm not 100% sure. I need to setup a test environment and reproduce the issue before I look at whether the documented workaround about setting the codepage is easy enough to use - or whether I can fix it some other way...

**Comment by DRSAgile** [comment]
Just in case: is it possible to get access to Microsoft.Win32 namespace, including the Registry class, via pulling it from .NET libraries? Maybe there is a way to wrap some DLL from there that provides the interface/API as an alternative to using "reg.exe". Not that I am calling for doing that since there are only a couple of cases like mine known, it would not worth the effort; just a theoretical question.

**Comment by shiftkey** [comment]
Here's the illustrated version of the current behaviour of the app:

<img width="1010" src="https://user-images.githubusercontent.com/359239/30093082-5c6dd560-9306-11e7-8b2b-d3040a5a9bc4.png">

**Comment by adamreisnz** [comment]
I am having the same issue on OS X. It used to work ok (I build Atom from master manually), but after today I built Github Desktop manually as well and now it's telling me it can't find Atom.

Is there a way to configure the app manually to point it to the location of Atom?

**Comment by shiftkey** [comment]
@adamreisnz

> Is there a way to configure the app manually to point it to the location of Atom?

We use the bundle identifier to look for Atom, so if the dev build is assigning something different than `com.github.atom` then it might be overlooked. Please open a fresh issue - it might be something like what @tierninho spotted here: https://github.com/desktop/desktop/issues/2551#issuecomment-325421097.

**Comment by shiftkey** [comment]
Closing this out as I think the original issue and unicode account name issue have been resolved.

**Comment by adamreisnz** [comment]
@shiftkey I download the latest version from the interwebs and that solve the problem. The self-built version was spewing a lot of EACCESS errors in the console. I'll ignore that and just use the publicly available versions.

**Comment by dobrescumihai19** [comment]
@shiftkey Can you please reveal what is the solution to this issue?

rsese has commented on [this atom issue](https://github.com/atom/atom/issues/15599#issuecomment-329051443) the fact that the opening of a repository in the atom editor should be addressed to this repository instead.

**Comment by shiftkey** [comment]
@dobrescumihai19 there's two things we check for as part of a valid Atom installation:

 - a registry entry at `HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom` containing these values:
  - `DisplayName=Atom`
  - `Publisher=GitHub, Inc.`
  - `InstallLocation` should look like `%LOCALAPPDATA%\atom`
 - a shim at `%LOCALAPPDATA%\atom\bin\atom.cmd`

One of the root causes found was that the installation didn't complete, and the `bin` folder didn't exist. I'm not sure where that ended up. 

The other was that the account name associated with the machine had non-ASCII characters in it, which meant the underlying tool we were using to poke at the registry returned malformed characters. We've fixed that in #2688, and it's available in `0.8.2`, so please confirm you're running that version and open a fresh issue with more information about your setup if you are still encountering issues.

**Comment by Ben3eeE** [comment]
@shiftkey Not the cause for @dobrescumihai19 since they did run the installer. But if someone is using the [portable version](https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) of Atom then these registry keys will not exist and `atom.cmd` will not be in `%LOCALAPPDATA%\atom\bin\`. Do you have any support for a portable mode install of Atom?

I'm just curious so I know which questions to ask users when we see these reports before sending them over to your repository :zap:

**Comment by shiftkey** [comment]
@Ben3eeE 

>  Do you have any support for a portable mode install of Atom?

Portable installation of these editors aren't supported currently. As an integrator with Atom and other tools I need to detect where they're located and ideally without users having to configure things - I'm open to suggestions about how to tackle this, if you have any ideas.

**Comment by shiftkey** [comment]
@Ben3eeE we're having a discussion about refining this support over in #2487 - feel free to add your feedback there for now.

**Comment by DRSAgile** [comment]
@shiftkey The version 0.8.2 still does not find Atom. I even re-installed Atom (though it was not necessary since we already checked above that both registry and all the paths necessary are set), but it did not help. 

The log file does not contain anything about it (there is a warning "2017-09-13T12:29:37.764Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}" but it is hardly related).

What else can we check in this case?

**Comment by Ben3eeE** [comment]
@DRSAgile What is your username? Or at least the non standard characters of the username?

**Comment by shiftkey** [comment]
I guess we need to add more diagnostics to this part of the codebase for scenarios we haven't encountered, but given how often we touch the registry to infer available editors and shells it shouldn't spam the log files unless really necessary.

**Comment by DRSAgile** [comment]
@shiftkey  If it necessary and possible, you might add a parameter to run the executable with additional logging to "desktop.production.log" so only those who need would be using it.

@Ben3eeE The complete list of CMD's archaic code pages should be supported for the fix in 0.8.1/2 to work: https://ss64.com/nt/chcp.html

**Comment by Ben3eeE** [comment]
@DRSAgile You're right. I'm just asking because knowing the username might help debugging if one of the developers can reproduce the issue locally. Do you have any symbols `&^#|`, or a space character, in your username?

**Comment by DRSAgile** [comment]
@Ben3eeE No, it is one word, no spaces, no special characters. Just basic alphabet characters, but they would belong to a different non-ANSI code page from the linked list. 
If I understand it right, the code should work equally well whether the code page is 437, 857, 861 or anything else from the list, so I am quite surprised that it does not (so far).

**Comment by dobrescumihai19** [comment]
@shiftkey

Thank you for your response.

I confirm that the Registry Entry is fine, including the `InstallLocation` Key that is set to the `C:\Users\Dobre\AppData\Local\Atom` Value.

I am also using the `C:\Users\Dobre\AppData\Local\Atom\Atom.exe` Executable Binary File Path as a workaround for another Issue that prevents `Atom`'s Tile to be pinned to the Start Screen and to the Task Bar and to be found by searching using the `Cortana` App.

The location of the `atom.cmd` File in the `C:\Users\Dobre` Folder is `C:\Users\Dobre\AppData\Local\Atom\app-1.20.0\resources\cli\atom.cmd` and not `%LOCALAPPDATA%\atom\bin\atom.cmd` as you have described.

The `%LOCALAPPDATA%\atom\bin` Folder does not exist.

This is the contents of the `%LOCALAPPDATA%\atom` Folder:

    Microsoft Windows [Version 10.0.16281.1000]
    (c) 2017 Microsoft Corporation. All rights reserved.

    C:\Users\Dobre>dir /o:gen/a/p %LOCALAPPDATA%\atom
     Volume in drive C is Windows
     Volume Serial Number is 94FA-41B2
    
     Directory of C:\Users\dobre\AppData\Local\atom
    
    13-Sep-17  04:36 PM    <DIR>          .
    13-Sep-17  04:36 PM    <DIR>          ..
    13-Sep-17  04:36 PM    <DIR>          packages
    13-Sep-17  04:35 PM    <DIR>          app-1.20.0
    13-Sep-17  04:16 PM           430,592 atom.exe
    11-Sep-17  05:40 AM         1,817,632 Update.exe
    13-Sep-17  04:36 PM           186,361 app.ico
    13-Sep-17  04:36 PM             1,244 SquirrelSetup.log
                   4 File(s)      2,435,829 bytes
                   4 Dir(s)  433,612,423,168 bytes free

If you are referring to the `Microsoft Windows` User Account Name, then it is either `Dobre` or `DobrescuMihai19@`_Server_`.com`.

I have previously modified the _User Variables for_ `Dobre` in order to append to the `%PATH%` Environment Variable the `C:\Users\Dobre\AppData\Local\Atom` Folder Path, which makes it possible for the `CygWin` `which` Command to locate the `atom.exe` Executable Binary File:

    C:\Users\dobre>which atom.exe
    /cygdrive/c/Users/Dobre/AppData/Local/Atom/atom.exe

After I have modified the `%PATH%` Environment Variable, I have updated the `GitHub Desktop Beta` Electron App to the 0.8.2 Version and then I have uninstalled and subsequently reinstalled the `Atom` Editor Electron App to the 1.20.0 x64 Version.

The issue still persists.

**Comment by Ben3eeE** [comment]
@dobrescumihai19 The Atom installer not creating the bin folder is a known issue /cc: https://github.com/atom/atom/issues/11450

Can you can try running `atom --squirrel-updated` from within the `%LOCALAPPDATA%\atom` folder? This should create the bin folder.

If this doesn't work then can you please comment in https://github.com/atom/atom/issues/11450 so we can into this some more?

**Comment by dobrescumihai19** [comment]
@Ben3eeE

Running the `atom --squirrel-updated` Command from within the `%LOCALAPPDATA%\atom` Folder has created the `bin` Folder:

Microsoft Windows [Version 10.0.16281.1000]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\dobre>cd "%LOCALAPPDATA%\atom"

C:\Users\dobre\AppData\Local\atom>atom --squirrel-updated

C:\Users\dobre\AppData\Local\atom>dir bin
 Volume in drive C is Windows
 Volume Serial Number is 94FA-41B2

 Directory of C:\Users\dobre\AppData\Local\atom\bin

13-Sep-17  08:26 PM    <DIR>          .
13-Sep-17  08:26 PM    <DIR>          ..
13-Sep-17  08:26 PM                68 apm
13-Sep-17  08:26 PM                65 apm.cmd
13-Sep-17  08:26 PM                75 atom
13-Sep-17  08:26 PM                58 atom.cmd
               4 File(s)            266 bytes
               2 Dir(s)  433,597,005,824 bytes free

This action has solved both issues:

1. The "_GitHub, Inc._" Folder has appeared in the "_Start Screen_" and it contains the "_Atom_" Tile and the "_GitHub Desktop_" Tile. The "_Cortana_" App now finds the "_Atom_" App while searching for it and it can be pinned to the "_Start Screen_" and to the "_Task Bar_".

2. In the "_GitHub Desktop_" Beta App, the "_Repository_" / "_Open in Atom_" Option finally works.

Thank you.

**Comment by shiftkey** [comment]
@dobrescumihai19 I'm glad you were able to get to the bottom of this issue.

**Comment by dobrescumihai19** [comment]
Thank you for helping, @shiftkey. However, as @mberasategi has already commented [here](https://github.com/desktop/desktop/issues/2585#issuecomment-326892624), it is extremely difficult to work right now this way. I am still inclined to use the "_Eclipse_" "_Oxygen_" I.D.E or maybe the pair formed by the "_Notepad++_" Editor and the "_SmartGit_" App that is unfortunately not free.

I guess that the fact that I have only 4 GB of RAM is significant in this respect. The "_Atom_" Editor is using around 200 MB of RAM even completely empty. It takes a few tens of seconds to load. Even if the RAM amount is increased, loading such huge quantities of data is slowing the Operating System down. Also, I believe that both the "_GitHub Desktop_" and "_Atom_" Apps can still be considered in their Beta stage.

These considerations have been noted on the following versions:

- "_Microsoft Windows 10 Home Edition_" Version 1709 (Operating System Build 16288.1) x64 © 2017.
- "_GitHub_" "_Atom_" Editor Electron App Version 1.20.0 x64.
- "_GitHub_" "_GitHub Desktop_" Beta Electron App Version 0.8.2 x64.

I wish you all good luck in your efforts.

**Comment by shiftkey** [comment]
> Also, I believe that both the "GitHub Desktop" and "Atom" Apps can still be considered in their Beta stage.

@mberasategi I'd love to get more details what you believe is missing from Desktop. We're close to 1.0, and we've got a [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) planned out for future updates, to give you an idea of where we're heading...

**Comment by mberasategi** [comment]
Thanks @shiftkey , but that issue with the text editor of choice was the only flaw I found. I left Atom for later on and I'm currently using Sublime (which is what I used otherwise), and everything is fine. So I'm quite happy with Desktop.

That quote was actually from @dobrescumihai19 , which was who you meant to mention, probably :wink:

**Comment by shiftkey** [comment]
@mberasategi you're right, I mentioned the wrong person. I've edited it again to clarify!

**Comment by dobrescumihai19** [comment]
I do not intend only to criticize without any serious reasons, @shiftkey. These are just the impressions coming from a view point that is not very familiar with both the "_Atom_" Editor Electron Desktop App and the "_GitHub Desktop_" Electron Desktop App. I apologize if I have offended any of you in any way.

I have restarted again the "_GitHub Desktop_" Electron Desktop App and I have attempted to remember what I felt that it was wrong. Again, the speed is not really satisfactory. On my machine, it is taking around twenty seconds to load.

Other than that, I remember having strange experiences that maybe were also due to the Operating System that is also enduring a continuous and apparently hazardous updating process. For instance, there was one time when I did not know how to start the "_GitHub Desktop_" Electron Desktop App. It used to work out alright previously, but during that certain period of time I have found that the only workaround was to start the "_Microsoft Edge_" Microsoft Universal Windows Platform App, to point it to a Repository and then to switch to the "_GitHub Desktop_" Electron Desktop App, as it was nowhere to be found either by the "_Cortana_" App or within the "_Start Screen_". A similar experience I had with the "_Atom_" Editor Electron Desktop App.

I guess that the issue went away upon an installation process of an update package.

Other than that, I have to admit that the "_GitHub Desktop_" Electron Desktop App looks extremely well and I do not remember it crashing at all. These points should indeed consist in reasons for it to qualify for the exit from its Beta stage.

Probably the fact that the "_Atom_" Editor Electron Desktop App that is already beyond the 1.0.0 Version is still having trouble installing itself correctly - for no obvious reason of the user - is still raising some questions. But then again, maybe the integration with the Operating System is not yet finished.

**Comment by shiftkey** [comment]
@DRSAgile I wonder if you're not also dealing with the same issue as #2735 - could you run `chcp` from your `cmd.exe` and see what it returns?

**Comment by DRSAgile** [comment]
It looks like the same issue as CHCP beside the code itself does return non-ASCII characters just as in the case you referenced to. So yes, if you are using Regex to read the code page, simply filtering out everything besides digits would be enough for this all to work without issue.

**Comment by shiftkey** [comment]
@DRSAgile cool, I'll close this out as I think that's the only outstanding issue here. #2759 should go out in the next update.

**Comment by shiftkey** [comment]
For anyone else who discovers this discussion, please open a fresh issue rather than commenting further if you encounter an issue with the Atom integration.

**Comment by BrainNotFoundException** [comment]
> @mberasategi The bin folder not being created or modified on install is a known issue with the Atom installer /cc: [atom/atom#11450](https://github.com/atom/atom/issues/11450)
> 
> You can try running `atom --squirrel-updated` from within the `%LOCALAPPDATA%\atom` folder. This should create the bin folder.

yea this works.
but for some reason i had to type atom --squirrel-update for it to work
