### ISSUE TITLE
Improve ease of configuring Git to work with corporate proxy

### ISSUE THREAD

**Issue by DanielKeogh** [desktop/desktop#2789]
### Problem statement

Clarified here: https://github.com/desktop/desktop/issues/2789#issuecomment-436290183

### Description

I used "Open In Desktop" on a repository via Firefox, but Desktop was unable to clone it. 

The error message:
Cloning into 'C:\Users\zzzz\Documents\GitHub\VsVim'...
fatal: unable to access 'https://github.com/zzzz/zzzz/': Failed to connect to github.com port 443: Connection refused
Error(s) during clone:
git clone failed: exit status 128

### Version
**GitHub Desktop version:** 1.0.0

**OS version:** Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

### Steps to Reproduce

1. Have a .pac based proxy.
2. Have no way to get to the internet other than the proxy.
3. Try and clone
4. Eventually it times out.

**Expected behavior:** Expected to clone repo to local machine

**Actual behavior:** Nothing

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@DanielKeogh currently you still need to tell Git about your proxy settings:

> git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080

Where `proxyuser` and `proxypwd` are your credentials, and `proxy.server.com:8080` is the server name and port you connect to.

**Comment by DanielKeogh** [comment]
If you just tell Git for me, I would really appreciate it. 👍

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by radumas** [comment]
I just want to point out how confusing this issue is for someone who downloads this application, has no configuration required, can login to Github successfully in the app and then.... can't use it. 

Surely the number of people who use Windows in a corporate environment and are behind a proxy is high (everyone I know in government).

**Comment by MuhammadFaizanKhan** [comment]
Any progress I am getting this error behind proxy.?

**Comment by ehale209** [comment]
Is there a non-command line option to fix this when using GitHub Desktop?  I'm in the same situation.  On my work laptop, and don't have a command-line option to enter something like:

>git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080

**Comment by joshaber** [comment]
Unfortunately configuring the proxy from the command line is the only solution I'm aware of.

**Comment by mapx-** [comment]
So, a windows user can access no command line, right ? or could I edit (or add) some config file in my github desktop ?

**Comment by joshaber** [comment]
Se https://git-for-windows.github.io to install Git on the command line for Windows.

**Comment by rcrodrix** [comment]
Thanks, joshaber! Installed it, and ran the command from shiftkey. All is well now. Much appreciated.

**Comment by jasminmurta70** [comment]
Thank you very much

2017-12-20 5:48 GMT+01:00 rcrodrix <notifications@github.com>:

**Comment by harshzalavadiya** [comment]
i have faced same problem after trying out one complete day got an easy solution(workaround)

double proxied it with nginx so my behind proxy git repository server is mapped to my local and gocd can do cloning it easily


	upstream corp_proxy  {
	    server corp_proxy:port; # your corporate proxy
	}
	
	location ~ ^/(git) {
	    proxy_buffering off;
	    proxy_pass_header on;
	    proxy_set_header Host "yoursite.com"; # don't add http etc
	    proxy_pass http://corp_proxy;
	}

**Comment by radumas** [comment]
So.... now that Microsoft owns GitHub....

**Comment by pallipavan** [comment]
i have .pac file
can you give the command how to set proxy (.pac file) to git?

**Comment by iAmWillShepherd** [comment]
> i have .pac file
>can you give the command how to set proxy (.pac file) to git?

For anyone else curious about ☝️, have a look at issue #5516.

**Comment by amayii0** [comment]
I also encountered that difficulty with GitHub Desktop 1.4.3

It was clearly not obvious to:
1/ Install GitHub Desktop without admin rights, deployed to C:\Users\this_is_me\AppData\Local\GitHubDesktop\app-1.4.3\GitHubDesktop.exe
2/ Login, see my repositories, fail to checkout
3/ Find this post
4/ Install Git for Windows WITH admin rights, deployed to C:\Program Files\Git\git-cmd.exe
5/ Find out how to get my proxy settings
5a/ They are not under HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings
5b/ Get AutoConfigURL from registry, which points to a wpad.dat
5c/ Analyse the wpad.dat to find out name of proxy server
6/ Finally use Git For Windows to type in the git config --global my_proxy_server:and_its_port

Hopefully community was contributing to this one :-)

**Comment by MuhammadFaizanKhan** [comment]
Well, it is proxy problem and i am able to solve this using 
`git cofig --global http.proxy mySystemIP:@ProxyIP:ProxyPort`

**Comment by billygriffin** [comment]
Reopening this issue as in one of our next few release, we'd like to explore how we can ease the pain of getting onboarded to GitHub Desktop when folks are working in an environment with a proxy.

I want to just clarify the primary problem statement, and find out if there's anything missing:

- When I download GitHub Desktop behind a proxy, I'm unable to use the app - requests just time out without a logical error message. I want GitHub Desktop to help get me over the hump of proxy configuration without me having to do some manual setup using the command line so that I can use the app normally.

**Comment by radumas** [comment]
Thanks for reopening this @billygriffin. I just want to flesh out the process more fully on a fresh workstation running Windows 10 Pro (64-bit) to show what is confusing to a user. I've installed the app from the `.exe` and am invited to Sign in to Github.com.

![image](https://user-images.githubusercontent.com/10623872/48085792-4198a900-e1c9-11e8-8b7a-8a1cfbfd86c0.png)

Success!

![image](https://user-images.githubusercontent.com/10623872/48085832-6260fe80-e1c9-11e8-8fa3-74decb694006.png)

Now to download a repository to work on it... I can see repositories on Github.com

![image](https://user-images.githubusercontent.com/10623872/48085878-7c9adc80-e1c9-11e8-8263-297d3de1db55.png)

That's odd... I was just seeing what was on Github.com! Why can't I download a repository

![image](https://user-images.githubusercontent.com/10623872/48085923-963c2400-e1c9-11e8-8719-7a3277d9efd9.png)

**Comment by amayii0** [comment]
Let's be clear.
The frustration comes from the fact we can see our repositories but not clone them.
This would mean there are two ways of setting up the connection:
1. For the GUI
2. For the clone (git internals?)

Since the workaround implies using `git` directly... you guess it.

**Comment by shiftkey** [comment]
@amayii0 Git does not have any built-in smarts to make it aware of your OS proxy settings (unless you set those via environment variables `HTTPS_PROXY` or `HTTP_PROXY`). That's why the config setting is the common solution to this.

The Electron UI however does detect this (I don't recall us having to do anything specific in the app).

**Comment by amayii0** [comment]
Agreed, that's the whole point. Have a view within the GUI over that kind of parameters.
I found it strange to install a tool, find an issue, solving the issue by installing another tool?!

**Comment by shiftkey** [comment]
> I found it strange to install a tool, find an issue, solving the issue by installing another tool?!

We recommend the config workaround using the `git config` command as it's a safer way than editing your `.gitconfig` manually, because Git will error on all operations if it cannot read your config. 

```shellsession
$ git status
fatal: bad config line 13 in file /Users/shiftkey/.gitconfig
```

For reference, this is what the config entry looks like after it's created:

```
[http]
	proxy = http://proxyuser:proxypwd@proxy.server.com:8080
```

If you feel confident to make those tweaks without the Git command line, go for it!

**Comment by amayii0** [comment]
The workaround did worked. But issue is that its not very user friendly :)

**Comment by Priyatham10** [comment]
> @DanielKeogh currently you still need to tell Git about your proxy settings:
> 
> > `git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`
> 
> Where `proxyuser` and `proxypwd` are your credentials, and `proxy.server.com:8080` is the server name and port you connect to.

It worked for me. Thank you so much.

**Comment by renu555** [comment]
This issue still persists. I cannot use the Github Desktop with proxy. Is there a way to input the proxy settings through GUI? This will be more user friendly and in line with the Windows Users who want to use Github Desktop without installing git.

**Comment by renu555** [comment]
Attaching Screenshot

**Comment by schlamar** [comment]
> This will be more user friendly and in line with the Windows Users who want to use Github Desktop without installing git.

You can configure the proxy in the C:\Users\[username]\.gitconfig file. No need to install git.

    [http]
        proxy = http://:@proxy.server.com:8080/

**Comment by renu555** [comment]
Thanks @schlamar
Resolved using
 [http]
    proxy = http://:@proxy.server.com:8080/
though I used the port different from 8080.

**Comment by schlamar** [comment]
@billygriffin I assume GitHub is using a local copy of Git for Windows if Git isn't installed?! Because there is an upstream report for automatic proxy configuration: https://github.com/git-for-windows/git/issues/1670

**Comment by rizwanjaved** [comment]
well, over here its get resolved by adding **github.com** in **/etc/hosts** file and restarting the webserver
would anybody explain to me how it's working? 
and one more thing first is saying 
`Failed to connect to github.com port 443: Network is unreachable`
After using sudo the error becomes 
`Could not resolve host: github.com`

**Comment by datalifenyc** [comment]
> 
> 
> I just want to point out how confusing this issue is for someone who downloads this application, has no configuration required, can login to Github successfully in the app and then.... can't use it.
> 
> Surely the number of people who use Windows in a corporate environment and are behind a proxy is high (everyone I know in government).

To be clear, for those that don't want to pass their username and password credentials, you can still use a combination of @DanielKeogh's git command and @schlamar's git config:

`git config --global http.proxy http://:@yourproxyserver:8080/`

**Comment by billygriffin** [comment]
Hi folks, just as an update we're actively working on making this easier and hopefully transparent for people using nonauthenticating proxies (which represent the majority of proxies as we understand it). We're hoping that this should be available in our next major release.

**Comment by billygriffin** [comment]
Since this is now shipped to beta in #9154 and the other associated issues, I'm going to close this issue.

**Comment by tierninho** [comment]
For those you who are interested you can download the beta version to get a head start on trying this new feature. Any feedback is much appreciated!

You will need to run a command to disable the workaround: `git config unset --global http.proxy` then download Beta: https://github.com/desktop/desktop#beta-channel, sign in, and you are good to go!

cc @datalifenyc @radumas @rizwanjaved @renu555 @schlamar @MuhammadFaizanKhan @amayii0 @DanielKeogh @nanojoey @priyanshnama  @AtomicCons

**Comment by billygriffin** [comment]
Hi all! @datalifenyc @radumas @rizwanjaved @renu555 @schlamar @MuhammadFaizanKhan @amayii0 @DanielKeogh @NanoJoey @priyanshnama @AtomicCons

I know you've already done the manual setup involved in getting this working, so apologies for the ask. 

Would you be willing to help us verify that what we're planning to release does actually work as intended by unsetting the proxy config and downloading the current [beta version](https://github.com/desktop/desktop#beta-channel)? We've done some manual testing, but verifying that it works from someone who actually experienced the problem first hand would be really helpful in giving us confidence that we're helping others who had the same problem y'all did.

Here are the steps:

1. Run `git config unset --global http.proxy` in the terminal
2. Download and install the [beta](git config unset --global http.proxy) version of Desktop
3. Run the beta version and clone any repo from GitHub
4. Ensure that fetching, pushing, or pulling works as expected

If it worked properly, using the beta version should just set the proper Git config proxy settings up for you and hopefully is transparent. Please let us know if you're able to test this, and we're happy to answer any questions about the steps if you have them. Thank you!

**Comment by DanielKeogh** [comment]
I would, but I'm not behind this kind of proxy any more.

**Comment by radumas** [comment]
https://github.com/desktop/desktop/issues/2789#issuecomment-600322141
> 
> 
> 
>     1. Run `git config unset --global http.proxy` in the terminal
> 

So I'm actually now running into the reverse issue, not necessarily using our proxy while WFH. I got an error message on this line that

```shell
git config unset --global http.proxy
error: key does not contain a section: unset
```

Also your link in Point 2 is wrong. I will test the new Beta when I am connected to our proxy though!

**Comment by billygriffin** [comment]
@radumas Apologies! I updated my comment. I believe the command should instead be `git config --global --unset http.proxy` and I updated the beta link to be the correct one. Sorry about that!

**Comment by mohammadyacn314** [comment]
just disable antivirus & firewall

**Comment by billygriffin** [comment]
This shipped in 2.4, so hopefully the vast majority of people using Desktop from behind a proxy it'll just work! Thanks for the input y'all. ❤️

**Comment by jshealth** [comment]
Doesn't work for me. I installed 2.4.3 over a previous version (from Nov 2019).
I'm connected to my internal network via VPN and then authenticated Proxy out to GitHub.
I'm on Windows 10
Git itself is working fine for remote operations with config `credential.helper=wincred` (I don't have any http.proxy settings in git itself, or in my shell (Powershell)). Proxy is set in Windows System Settings with a pac script.
So if I try to pull from a remote on Github with Github Desktop I get
"fatal: unable to access 'https://github.com....': Received HTTP code 407 from proxy after CONNECT"
but if I choose from Github Desktop "Repository > Open in Powershell" and then do `git pull`, it works fine, with no need to type username / password, since they are stored in Windows Credential Manager and git is configured to use wincred for credential.helper

**Comment by NotAProfessionalDeveloper** [comment]
Neither using .gitconfig nor the corresponding Git command make it use the proxy.

```
[http]
	proxy = http://user:pass@proxy.example.com:80
[https]
	proxy = http://user:pass@proxy.example.com:80
```
(Yes the last line is correct, we are using HTTP CONNECT to tunnel HTTPS across the HTTP connection)

The connection to the proxy is made but a 407 is returned because no credentials are sent. (There is no Proxy-Authorization: header at all in the request to the proxy.)

**Comment by TomF475** [comment]
I don't believe this issue is fixed as it's not working for me either.

I've just installed v2.9.6 and although I've been able to sign in to GitHub Desktop I can't even clone any repos. I continue to get the "Received HTTP code 407 from proxy after CONNECT" error.

Updating gitconfig with proxy details, either with or without credentials, makes absolutely no difference, the same error is returned.

**Comment by steveward** [comment]
@TomF475 the 407 error usually indicated that your credentials are not being accepted. Can you verify you configured the proxy settings correctly in your .gitconfig?

**Comment by TheNetworkIsDown** [comment]
Why are we even discussing this here. The issue is closed. Why is it closed?!

**Comment by jshealth** [comment]
Agree, with @NotAProfessionalDeveloper @TomF475 I posted after the issue was closed because it was not resolved for me.
I just ended up not using GitHub Desktop.

**Comment by amayii0** [comment]
> Agree, with @NotAProfessionalDeveloper @TomF475 I posted after the issue was closed because it was not resolved for me. I just ended up not using GitHub Desktop.

Same as @jshealth, Visual Studio Code is enough for me.
[Atlassian Sourcetree](https://www.sourcetreeapp.com/) when going  fancy.
![image](https://user-images.githubusercontent.com/9150547/153303619-60414f25-df86-4ead-ac96-1f318740b29e.png)

**Comment by zeocax** [comment]
FYI, if you still face some problem on the proxy with git (like me), this issue may be caused by git's default anyauth proxy setting. It fails if the proxy doesn't respond to the initial request with a standard 407 challenge. While this challenge-response behavior from git is compliant with RFC 7235, some proxies may not follow this specific flow.

The fix is to force git to use Basic auth proactively with this command:

```bash
git config --global http.proxyAuthMethod 'basic'
```
