### ISSUE TITLE
Opening repository in Git Bash results in catastrophic error

### ISSUE THREAD

**Issue by gilmae** [desktop/desktop#3882]
## Description
Unable to open repository in Git Bash from the desktop app. Restarting the app results in the same error every time.

### Version
Version: 1.0.13
OS: Windows 10.0.16299

### Replication Steps
Expected behavior: Opened in Git Bash
Actual behavior: Error on the desktop app
Reproduces how often: 100%

#### Logs
Error: spawn where ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 1.0.13
OS: Windows 10.0.16299

Related to #3825

**Comment by shiftkey** [comment]
@gilmae I've not had a chance to look into this due to #3825 being challenging to implement correctly without `START`, but I've published an update to the [beta channel](https://github.com/desktop/desktop#beta-channel) which catches this error and adds some better tracing around launching shells.

If you're able to open this up, trigger the error and look at the logs there should be some more detail about how your setup differs to mine.

If you don't have time to switch, this will land in the stable channel next week.

**Comment by gilmae** [comment]
[2018-02-18.desktop.beta.log](https://github.com/desktop/desktop/files/1734516/2018-02-18.desktop.beta.log)

Log attached from trying to open a repo in Git Bash.

Same results as described in issue description.

**Comment by shiftkey** [comment]
@gilmae thanks for confirming the app now doesn't crash. 

I'm curious why [this message](https://github.com/desktop/desktop/blob/master/app/src/lib/shells/win32.ts#L139) isn't being logged as that would have told me what it was trying to spawn.

We rely on Git for Windows adding a certain registry key that points to it's install location. To see what's set on your machine, you can run this command in PowerShell:

```
PS C:\Users\shiftkey> Get-ItemProperty HKLM:\Software\GitForWindows

CurrentVersion : 2.16.1
InstallPath    : C:\Program Files\Git
LibexecPath    : C:\Program Files\Git\mingw64\libexec\git-core
PSPath         : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\GitForWindows
PSParentPath   : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software
PSChildName    : GitForWindows
PSDrive        : HKLM
PSProvider     : Microsoft.PowerShell.Core\Registry
```

In theory, the `InstallPath` key should point to the install directory, with `git-bash.exe` under that directory. We're not checking that when launching, which I think is how the ENOENT occurring.

I've published a test build containing the tracing from in #3975 [here](https://s3.amazonaws.com/github-desktop/releases/1.0.14-test3-5672e55e/GitHubDesktopSetup.exe) - would you mind trying out that version?

On my machine the log look like this when it successfully launches Git Bash:

```
2018-02-19T00:30:30.737Z - info: [ui] [AppStore] loading 5 repositories from store
2018-02-19T00:30:31.232Z - info: [ui] launching: 1.0.14-test3 (Windows 10.0.16299)
2018-02-19T00:30:31.232Z - info: [ui] execPath: 'C:\Users\shiftkey\AppData\Local\GitHubDesktop\app-1.0.14-test3\GitHubDesktop.exe'
2018-02-19T00:30:43.549Z - info: [ui] launching Git Bash at path: "C:\Program Files\Git\git-bash.exe"
```

I'm curious how your machine differs to mine when this error occurs. If `git-bash.exe` doesn't exist there (my best guess so far) I'd love to understand how that might have happened.

**Comment by gilmae** [comment]
Sorry if I miscommunicated, but the application definitely still crashes when opening any shell.

**Comment by shiftkey** [comment]
@gilmae with the crash dialog? Could you attach a screenshot of what you see?

**Comment by shiftkey** [comment]
@gilmae I've had a chance to read your log file again and I see the problem:

```
Error: spawn where ENOENT
```

This isn't related to launching Git Bash, but is related to the work to resolve Git on your PATH:

https://github.com/desktop/desktop/blob/f84e926f2886724c181ac57385a541dc243a50f7/app/src/lib/is-git-on-path.ts#L14

`where` is located at `C:\Windows\System32\where.exe`, so this it's the same root cause as #3825 but just manifesting elsewhere. This can be fixed independent to the root cause of correctly spawning `cmd`.

**Comment by gilmae** [comment]
I can confirm that after manually adding "c:\windows\system32" to PATH that opening the repository in Git Bash works.

For reference, the requested screenshot is also attached:
![image](https://user-images.githubusercontent.com/46712/36407021-3963a6a4-164f-11e8-8a21-340109c3d280.png)
