### ISSUE TITLE
Maximize window state will show a gap on top

### ISSUE THREAD

**Issue by d2phap** [desktop/desktop#5033]
## Description
When I maximize the window, there is a gap above the fake title bar.
Apply to: 
* dragging title bar, 
* clicking on maximize button, 
* using hotkey `Win + Up`
* double clicking on title bar

## Version
* GitHub Desktop: 1.2.6
* Operating system: 10.0.17134.112 x64

## Steps to Reproduce
1. Open GitHub in normal window state
2. Maximize the window. The issue occurs.
3. Restore window state to normal
4. Maximize the window again, there is no issue.
5. Keep repeating this, the issue will happen again.

### Expected Behavior
There is no gap on top of the window

### Actual Behavior
There is a gap which is title bar location on top of window

## Additional Information
![image](https://user-images.githubusercontent.com/3154213/41884945-44f94c80-7928-11e8-8a56-60e0f9dd7b4d.png)

**Comment by shiftkey** [comment]
@d2phap thanks for the report. I've been able to reproduce this with the light and dark theme, and sometimes the window does maximize to the full space, other times it'll leave some space below - I changed my background to green to show it's a mixture of available window height and white drawn above the header:

<img width="1440" src="https://user-images.githubusercontent.com/359239/41909451-6ba11404-791d-11e8-86bd-40f52c52c67e.png">

**Comment by j-f1** [comment]
@shiftkey does the web inspector show the white stripe as part of the page or is it separate?

**Comment by shiftkey** [comment]
@j-f1 it does not (I expect all the window to be tinted blue here)

<img width="487" src="https://user-images.githubusercontent.com/359239/41910726-e9d68ef0-7920-11e8-84f1-8756ce2be80c.png">

Adding `electron` to indicate this might be a framework issue to dig into.

**Comment by shiftkey** [comment]
After digging into this a bit further I think this is a problem with how Electron handles the events. Maybe this has been fixed, but here's my setup so far:

 - make these changes to `master`


```diff
diff --git a/app/src/lib/stores/app-store.ts b/app/src/lib/stores/app-store.ts
index 8adcaa199..fa1963aed 100644
--- a/app/src/lib/stores/app-store.ts
+++ b/app/src/lib/stores/app-store.ts
@@ -315,7 +315,8 @@ export class AppStore extends TypedBaseStore<IAppState> {
   private wireupIpcEventHandlers(window: Electron.BrowserWindow) {
     ipcRenderer.on(
       'window-state-changed',
-      (event: Electron.IpcMessageEvent, args: any[]) => {
+      (event: Electron.IpcMessageEvent, state: WindowState) => {
+        log.warn(`window-state-changed: ${state}`)
         this.windowState = getWindowState(window)
         this.emitUpdate()
       }
diff --git a/app/src/ui/index.tsx b/app/src/ui/index.tsx
index ad88a9b79..3c6e59865 100644
--- a/app/src/ui/index.tsx
+++ b/app/src/ui/index.tsx
@@ -151,7 +151,34 @@ dispatcher.registerErrorHandler(missingRepositoryHandler)
 
 document.body.classList.add(`platform-${process.platform}`)
 
-dispatcher.setAppFocusState(remote.getCurrentWindow().isFocused())
+const currentWindow = remote.getCurrentWindow()
+
+dispatcher.setAppFocusState(currentWindow.isFocused())
+
+window.addEventListener('resize', resizeThrottler, false)
+
+let resizeTimeout: number | null = null
+function resizeThrottler() {
+  // ignore resize events as long as an actualResizeHandler execution is in the queue
+  if (!resizeTimeout) {
+    resizeTimeout = window.setTimeout(function() {
+      resizeTimeout = null
+      actualResizeHandler()
+
+      // The actualResizeHandler will execute at a rate of 15fps
+    }, 66)
+  }
+}
+
+function actualResizeHandler() {
+  if (currentWindow.isMaximized()) {
+    const [x, y] = currentWindow.getPosition()
+    const bounds = currentWindow.getContentBounds()
+    log.warn(
+      `maximized position: [${x}, ${y}] - bounds: ${JSON.stringify(bounds)}`
+    )
+  }
+}
 
 ipcRenderer.on('focus', () => {
   const { selectedState } = appStore.getState()
```

When you run the app up and switch between maximized and normal state using `WinKey + Up Arrow` you'll notice this pattern in the logs:

<img width="824" src="https://user-images.githubusercontent.com/359239/41989599-3c7cbe7c-7a16-11e8-8877-28c7e6549c58.png">

Note that we're only listening to these window change events, and I don't think we're setting these bounds anywhere.

The next step is to upgrade to Electron 2.0.x and see if it's been fixed there.

**Comment by shiftkey** [comment]
Still reproducible on Electron 2.0.3, and the essence of the problem is this:

- When maximized correctly, the position of the window is this: `maximized position: [-8, -8] `
- When not maximized correctly, the position of the window is this: `maximized position: [-8, 9]`

That difference of 17px is the additional space that's currently wasted on every other maximize. This doesn't seem to occur on `electron-quick-start` (which is `2.0.0`, but does not use a [Frameless Window](https://electronjs.org/docs/api/frameless-window) like Desktop does).

**Comment by shiftkey** [comment]
Reported upstream https://github.com/electron/electron/issues/13466

**Comment by philipmontgomery** [comment]
Still happening for me on 1.3.3 after the update. Every other normal to maximize click shows the space at the top.

**Comment by shiftkey** [comment]
@philipmontgomery can you provide details about your OS setup? [This issue](https://github.com/Microsoft/vscode/issues/52265#issuecomment-410531924) indicates that Microsoft have put out an update for Windows 10 that might address your setup.

**Comment by ahkohd** [comment]
> @philipmontgomery can you provide details about your OS setup? [This issue](https://github.com/Microsoft/vscode/issues/52265#issuecomment-410531924) indicates that Microsoft have put out an update for Windows 10 that might address your setup.

Well I too faced the same problem, I keep searching on solution but none worked.
So I decided to write a work around, and it worked. The solution is quite simple.
maximize: resize window to screen size and set window position to top, left (0, 0)
unmaximize: resize window to a window size and position which was saved when the maximize function was invoked.

**How it works**
1. You will need to write a custom, maximize and unmaximize/restore event handler using ``ipcMain`` in your main thread.
2. Write a custom maximize and minimize function in your render process to emit event to your main process to invoke the custom maximize/unmaximize event handler function.

The code


```
const {ipcMain} = require('electron');
// to store the restore window screen width and height and position...
let restoreWindowSave;

main thread i.e ``electron.js``
....

function createWindow () {
  // Create the browser window logics.
 let  win = new BrowserWindow({ width: 800, height: 600 })


// set initial window width, height and positon
	restoreWindowSave =	mainWindow.getBounds();

// custom maximize and unmaximize event handler logics...
ipcMain.on('custom-maximize', (event, x, y, restoreDetails) => {
		restoreWindowSave = restoreDetails;
		 mainWindow.setSize(x,y)
		 mainWindow.setPosition(0, 0);
	  });
	  
	  ipcMain.on('custom-restore', (event) => {
		
		 mainWindow.setSize(restoreWindowSave.width, restoreWindowSave.height)
		 mainWindow.setPosition(restoreWindowSave.x, restoreWindowSave.y);
	  })



....
```

in your render process i.e ``render.js``
```
import { remote, screen, ipcRenderer } from 'electron';
customMaximize()
    {
     
       // windows dimension and positon {width, height, x, y}
        let resDetails = remote.getCurrentWindow().getBounds();
              // use ipcRender to send custom-resize event to main thread to invoke the custom resize event handler to resize the window....
        ipcRenderer.send('custom-maximize', this.screenSize.width, this.screenSize.height, resDetails);
    }

    customRestore()
    {
        ipcRenderer.send('custom-restore');   
    }

// just to test it out...
let btnMax = document.getElementById('btn-max');
let btnRes = document.getElementById('btn-res');

btnMax.addEventListener('click', function (e) {
        e.preventDefault();
       customMaximize();
    });

btnRes.addEventListener('click', function (e) {
        e.preventDefault();
       customRestore();
    });

```
to test it out create maximize and unmaximize button in your view.
```
<button id="btn-max">Maximize</button>
<button id="btn-res">Unmaximize/Restore</button>
```
