### ISSUE TITLE
Unexpected behaviour pressing enter/return on Clone a Repository options dialog

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#5234]
## Description

When pressing enter/return on Clone a Repository options dialog the behaviour is unexpected and confusing 

## Version

* GitHub Desktop: 1.2.6

* Operating system: macOS 10.13.6 (17G65)

## Steps to Reproduce

1. _Clone_ a repo from GitHub website
2. Look at the _Clone a Repository_ dialog
3. Press _Enter_

### Expected Behavior

Enter should choose the default blue Clone button

### Actual Behavior

Enter activates the GitHub.com tab

## Additional Information

![screen shot 2018-07-24 at 14 25 49](https://user-images.githubusercontent.com/49612/43141604-3b6221ba-8f4e-11e8-92ea-52a39f3c559a.png)

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇

**Comment by RobertJGabriel** [comment]
@iAmWillShepherd Mind If I have a go at this?

**Comment by iAmWillShepherd** [comment]
@RobertJGabriel sure thing! Just be sure to cc me on your PR whenever you submit it.

**Comment by RobertJGabriel** [comment]
Sweet, will give it a go now.

**Comment by gingerbeardman** [comment]
@RobertJGabriel did you get anywhere with this? It just caught me out again.

**Comment by RobertJGabriel** [comment]
Sorry, @gingerbeardman . I forgot to update. Been up the walls at work recently. I will have a look tonight but if someone wants to have a look too feel free :)

**Comment by kanishk98** [comment]
@gingerbeardman Hi. I've been exploring Desktop the past couple of days and I'm interested in working on this issue. Is it okay if I have a look at this?

**Comment by gingerbeardman** [comment]
Fine by me, courtesy mention @RobertJGabriel

**Comment by kanishk98** [comment]
I'm facing problems reproducing the issue on my system. @gingerbeardman can you help me with this?

![screen shot 2018-09-16 at 3 09 22 pm](https://user-images.githubusercontent.com/24617297/45595065-78212700-b9c3-11e8-9105-4a87e03f51fa.png)

Hitting the enter/return key gives me

![screen shot 2018-09-16 at 3 08 43 pm](https://user-images.githubusercontent.com/24617297/45595063-735c7300-b9c3-11e8-97c7-13de87c69175.png)

### Software versions

macOS: High Sierra (10.13.6)
Version: 1.3.5

Is it safe to assume that the update may have been fixed by an update already?

**Comment by gingerbeardman** [comment]
I'm on 1.4.0 and still see it?

Did you carry out my steps to reproduce in the OP?

**Comment by kanishk98** [comment]
@gingerbeardman Sorry, I definitely messed up while trying to follow the steps to reproduce the issue. I just checked this on a Windows 10 machine running Desktop 1.4.0 and the problem definitely exists. I'll start looking. 
Again, sorry for the mistake.

**Comment by gingerbeardman** [comment]
no worries at all!

**Comment by JakeHL** [comment]
Did anyone get anywhere with this? I can take a look

**Comment by tierninho** [comment]
@JakeHL As it's been a few weeks, feel free. 

@kanishk98 If you have a PR pending, please let us know 😄 

Thanks, all!

**Comment by JakeHL** [comment]
The tab bar seems to be stealing focus after launching the modal for the first time - I've been trawling through the components in this modal to see if/why focus would be stolen but I'm a little stumped, anyone got an idea?

**Comment by gingerbeardman** [comment]
This is still an issue that catches me out almost every time I create a new repo from a URL (often)
