### ISSUE TITLE
Long changelog text exceeds bounderies in client

### ISSUE THREAD

**Issue by Laumania** [desktop/desktop#5854]
## Description
Long changelogs are shown 'wierd' in the client and text exceeds the bounderies.
Seen on Windows client, not tested on Mac.

## Version
Windows client v1.4.2.
Operating system: Windows 10

## Steps to Reproduce
When a new update in notified in the top of the client, click the "What's new" link, and the dialog shows from the screenshot.

### Expected Behavior
I would except the changelog to be inside the windows it's displayed in, so I guess I would except there to be a scroll if the text was longer - as the sample was in my case.

### Actual Behavior
![image](https://user-images.githubusercontent.com/1378458/46650438-d0031600-cb9c-11e8-829d-960ffafa8ea3.png)

## Additional Information
None.

### Logs
I don't think logs are nessesarily to see this issue.

**Comment by billygriffin** [comment]
@Laumania Thanks for the report! This should be fixed in 1.4.3 later this week, sorry about that! And big thanks to @amarsiingh for fixing it!

**Comment by amarsiingh** [comment]
@billygriffin I suppose the reported issue here is different from #5760 (which referred to T&C and Licenses dialogs)
I've verified and a fix for this issue ready. If you can reopen this issue I'll create PR for review.

**Comment by billygriffin** [comment]
Apologies @amarsiingh, thanks for the clarification. ❤️

**Comment by amarsiingh** [comment]
thanks @billygriffin. I've created the PR with the fix.

**Comment by simonh-mmw** [comment]
Updated to 1.4.3 today and found this issue to still exist.

Version, steps, and behaviour the same as above.

![githubdesktop bugfix](https://user-images.githubusercontent.com/36480033/47213364-aadb8800-d392-11e8-905a-3f5f3f01f6c6.png)

**Comment by shiftkey** [comment]
@simonh-mmw thanks for the update!

Unfortunately you were using 1.4.2 at the time it displayed this "new update ready!" prompt, which still had this issue. #5885 was merged into 1.4.3, and should mean this goes away for the next "new update ready!" prompt...

**Comment by staabm** [comment]
same here:

![image](https://user-images.githubusercontent.com/120441/47254256-44bd3680-d460-11e8-91d7-a1d2fa936a81.png)
