### ISSUE TITLE
macOS Catalina Error

### ISSUE THREAD

**Issue by cby3149** [desktop/desktop#8573]
### Describe the bug

Can't Push Origin

### Version & OS

MacOS: 10.15.1
GitHub Desktop: 2.2.2

### Actual behavior

It pumps out an error message.

### Screenshots

<img width="579" alt="image" src="https://user-images.githubusercontent.com/46272347/68079934-4f770f00-fdc8-11e9-8f63-6b55357ad703.png">

### Logs

dyld: Library not loaded: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf-lite.dylib
  Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/WirelessDiagnostics
  Reason: Incompatible library version: WirelessDiagnostics requires version 1.0.0 or later, but libprotobuf-lite.dylib provides version 0.0.0
/Applications/GitHub Desktop.app/Contents/Resources/app/static/ask-pass-trampoline.sh: line 3:  4432 Abort trap: 6           ELECTRON_RUN_AS_NODE=1 "$DESKTOP_PATH" "$DESKTOP_ASKPASS_SCRIPT" "$@"
error: unable to read askpass response from '/Applications/GitHub Desktop.app/Contents/Resources/app/static/ask-pass-trampoline.sh'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by cby3149** [comment]
All things work well on MacOS Mojave.

**Comment by outofambit** [comment]
hi @cby3149, i'm sorry you're having this issue! we're tracking this at #8506 (and there's an in-progress fix at #8555). hoping to have this resolved soon. in the meantime, if you control click on the app and select 'Open', that should get you around the issue.

**Comment by outofambit** [comment]
Hi again @cby3149. After looking at this again, I believe this is a different issue than #8506. To make sure I'm understanding right, this only happens when you try to push from GitHub Desktop? Is it only with a specific repo, or all of them?

Could you include a log file from this issue? You can find them from Desktop with `Help` > `Show Logs In Finder`. Thank you!

**Comment by billygriffin** [comment]
One other thought @cby3149 is that this might be a known issue documented here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

Would you mind checking that out and seeing if any of those solutions might be causing it and whether you're able to get it fixed with the suggestions provided?

**Comment by outofambit** [comment]
Hi @cby3149! We've just released a new version of desktop with some compatibility improvements for Catalina. If you could update and see if this is still an issue, that would be really helpful. Thanks!

**Comment by cby3149** [comment]
> Hi @cby3149! We've just released a new version of desktop with some compatibility improvements for Catalina. If you could update and see if this is still an issue, that would be really helpful. Thanks!

Hi @outofambit ! After reinstalling Catalina, everything works again. It is weird to encounter this issue. Actually, I can push and pull using git command. Thanks again! I think this issue can close now.

**Comment by samrawson66** [comment]
I am still having issues with the push.  Fails about 20 times and then inexplicably just works!  So frustrating

**Comment by tierninho** [comment]
@samrawson66 Please open a new issue https://github.com/desktop/desktop/issues/new?template=bug_report.md if you need assistance. Thank you.
